README.md

- This is a proposal to standardize the look and feel of README files for jest-community repos.
- I think we can start by just standardizing the header, which is what this PR does
- I borrowed it from webpack-contrib, for example https://github.com/webpack-contrib/css-loader and https://github.com/webpack-contrib/sass-loader
thoughts? @orta @thymikee @SimenB

[Proposal] Standarize header in README

---

README.md

https://github.com/jest-community/eslint-plugin-jest/pull/11#issuecomment-344406682

Use the current ESLint logo

---

rules/__tests__/prefer_to_be_undefined.test.js
rules/prefer_to_be_null.js
rules/prefer_to_be_undefined.js
rules/prefer_to_have_length.js
rules/util.js

Refactor prefer rules

---

rules/__tests__/prefer_to_be_null.test.js
rules/util.js

fix: add argument node checks

---

rules/__tests__/prefer_to_be_undefined.test.js
rules/util.js

fix: add null guards on argument selectors

---

index.js

Add the 'jest' plugin and 'jest/globals' environment to the recommended
config so the user doesn't have to include these manually.

feat(recommended): Add plugin and globals env

---

.travis.yml
package.json
yarn.lock

chore: update jest to version 22

---

rules/__tests__/valid-describe.test.js
rules/valid-describe.js

Resolves #75
Forgot this case in the original PR, and perhaps something to consider adding to our util module (#73).

fix(valid-describe): support TemplateLiteral first argument

---

.travis.yml
package.json
rules/__tests__/no-disabled-tests.test.js
rules/no-disabled-tests.js
rules/util.js

It would be great if we could get to 100% coverage, especially as we're so close!
Missing a couple of branches in utils.js, but I've also added a couple of ignores I would like to drop. Help appreciated!
Missing coverage:

fix(coverage): get close to 100% test coverage

---

package.json
rules/no-focused-tests.js
rules/util.js

Regarding #86, this should get us to 100% coverage.

Get full test coverage

---

docs/rules/lowercase-name.md
rules/__tests__/lowercase-name.test.js
rules/lowercase-name.js

This PR adds the `ignore` option discussed in #76.

feat(lowercase-name): add 'ignore' option (#76)

---

rules/__tests__/no-jest-import.test.js
rules/no-jest-import.js

fixes #114, includes tests, hope it helps

fix(rules): don't crash on require() (#114)

---

docs/rules/expect-expect.md

fix(docs): fixed typo

---

.travis.yml
package.json
yarn.lock

chore: simplify semantic-release a bit

---

README.md

Use real Jest logo

---

rules/__tests__/no-focused-tests.test.js
rules/no-focused-tests.js

Detect usage like 'fit.each()'

---

rules/__tests__/prefer-spy-on.test.js
rules/prefer-spy-on.js

fix(prefer-spy-on): fix Cannot read property 'type' of undefined

---

rules/__tests__/valid-expect-in-promise.test.js
rules/valid-expect-in-promise.js

[updated]
Excludes new expressions for the `new Promise` case. Test added from issue and test case added

fix(valid-expect-in-promise): fix type exception (#195)

---

dangerfile.js

This came up in a discussion on #207 so I split this change off into a separate PR.

Danger fails for new rules without README changes

---

README.md

As titled, it seems that they moved the asset.

Fix up eslint logo

---

src/rules/__tests__/no-test-return-statement.test.ts
src/rules/no-test-return-statement.ts

I've checked the meta information :)

ts-migration/no-test-return-statement

---

src/rules/__tests__/no-duplicate-hooks.test.ts
src/rules/no-duplicate-hooks.ts

ts-migration/no-duplicate-hooks

---

.gitignore

b/c I'm sick of it not being ignored.
I figured I'd take the safe route of a PR rather than committing directly to master 😬

Update .gitignore to include .idea/

---

src/processors/__tests__/snapshot-processor.test.ts
src/processors/snapshot-processor.js
src/processors/snapshot-processor.ts

Figured I might as well break this out

ts-migration/snapshot-processor

---

src/rules/prefer-todo.ts
src/rules/tsUtils.ts

Based off #375 - I didn't base it off master as it'll cause a merge conflict either way.

Improve prefer todo again

---

src/rules/__tests__/valid-describe.test.ts
src/rules/tsUtils.ts
src/rules/valid-describe.ts

Bit of a general improvement & consolidation.

Improve valid describe

---

src/rules/tsUtils.ts

Minor, but important none the less.

improve isExpectCall guard & interface

---

src/rules/no-test-callback.ts
src/rules/prefer-to-have-length.ts
src/rules/prefer-todo.ts
src/rules/tsUtils.ts
src/rules/valid-expect-in-promise.ts

chore: clean up istanbul ignores

cleanup-istanbul-ignores

---

src/rules/tsUtils.ts

chore(tsutils): remove duplicate interface

remove duplicate interface

---

babel.config.js

chore(babel): add `todo` about converting to typescript

add todo to babel config

---

README.md

I missed this when reviewing #434 😬

add link to `valid-title` in readme

---

README.md
docs/rules/valid-title.md
src/rules/utils.ts
src/rules/valid-title.ts

Don't mind me - just cherry picking a few things from `next` into `master` to reduce the diff & changes :D

Cherry pick from next 1

---

src/rules/__tests__/no-empty-title.test.ts
src/rules/__tests__/no-identical-title.test.ts
src/rules/__tests__/valid-title.test.ts
src/rules/no-empty-title.ts
src/rules/no-identical-title.ts
src/rules/valid-title.ts

Now we report on the actual title, rather than the jest function.

Improve error locs for title based rules

---

README.md
src/index.ts

@G-Rath @jeysal @thymikee thoughts? I'd like to add `no-test-callback` as well, but it might be too much?

chore: update recommended config

---

src/rules/__tests__/valid-title.test.ts
src/rules/valid-title.ts

fix(valid-title): ignore string addition

---

.github/workflows/lint.yml
.github/workflows/nodejs.yml
.github/workflows/release.yml
README.md

@SimenB Turns out that the default is to look for `commitlint.config.js`, and to pass if it's not found 😬

ci(lint): pass `configFile` to `commitlint` action

---

src/rules/expect-expect.ts

fix(expect-expect): use `u` flag in regex

---

src/rules/utils.ts

This'll hopefully be the last time :joy:

chore: remove duplicated interface

---

src/rules/__tests__/valid-title.test.ts
src/rules/valid-title.ts

fix(valid-title): ensure argument node is defined before accessing props

---

.github/workflows/nodejs.yml
babel.config.js
package.json
tsconfig.json

BREAKING CHANGE
@SimenB I made sure to spell it correctly this time 😜

feat: drop support for node 8

---

docs/rules/no-deprecated-functions.md

I missed this one as it was added after I did the docs updating 😬

docs(no-deprecated-functions): add missing code quotes

---

src/rules/__tests__/lowercase-name.test.ts
src/rules/lowercase-name.ts

fix(lowercase-name): ignore all top level describes when option is true

---

docs/rules/expect-expect.md
src/rules/__tests__/expect-expect.test.ts

docs(expect-expect): add example of escaping special regexp character

---

src/rules/__tests__/no-if.test.ts

I'm going to slowly convert all of our test cases to be in this format for consistently 🎉

test(no-if): use dedent for all cases

---

src/rules/__tests__/valid-describe.test.ts

test(valid-describe): use dedent for multi-line cases

---

src/rules/__tests__/expect-expect.test.ts

test(expect-expect): use dedent for multi-line cases

---

src/rules/__tests__/prefer-hooks-on-top.test.ts
src/rules/__tests__/prefer-todo.test.ts
src/rules/__tests__/require-to-throw-message.test.ts
src/rules/__tests__/require-top-level-describe.test.ts

Use dedent some more

---

docs/rules/valid-title.md

docs(valid-title): reduce ambiguity

---

.github/workflows/lint.yml
.github/workflows/nodejs.yml
.github/workflows/release.yml

chore: use v14 LTS for more tests and release

---

docs/rules/no-hooks.md

docs(no-hooks): remove broken link

---

docs/rules/expect-expect.md

docs(expect-expect): fix typo

---

src/rules/__tests__/require-top-level-describe.test.ts
src/rules/require-top-level-describe.ts

fix(require-top-level-describe): handle `describe.each` properly

---

README.md

This PR is a replacement for #580
Thank you for a ping @G-Rath hopefully this time it gets merged 🙂
Fixes #222

Add eslint plugin istanbul

---

src/rules/__tests__/utils.test.ts

I realised we can easily test `getNodeName` now; since we have access to the "source code" (and that that source code is required to be a single line of code for unit testing) it's easy to figure out what the expected value should be using simple regexp.

test(utils): add test for `getNodeName`

---

docs/rules/unbound-method.md

docs(unbound-method): replace `extends` with `plugins`

---

.github/workflows/nodejs.yml
package.json

An attempt to set up prereleases from `next`

chore: make pre-releases from next branch

---

docs/rules/no-conditional-expect.md

Based on my comment [here](https://github.com/jest-community/eslint-plugin-jest/issues/295#issuecomment-583788671).
Closes #295

docs(no-conditional-expect): add section on how to catch errors for testing

---

README.md

Noticed it was HTTP and also has been moved 0:-)

docs: fix ESLint link

---

src/rules/utils.ts
yarn.lock

chore: update `@typescript-eslint` packages

---

.github/workflows/smoke-test.yml

It's really not my week apparently...

ci: point smoke test at correct config file

---

CHANGELOG.md
README.md
docs/rules/no-conditional-in-test.md
docs/rules/no-if.md
package.json
src/__tests__/__snapshots__/rules.test.ts.snap
src/__tests__/rules.test.ts
src/rules/__tests__/no-conditional-in-test.test.ts
src/rules/no-conditional-in-test.ts
src/rules/no-if.ts

next -> main

---

docs/rules/prefer-expect-assertions.md

Noticed this while working on #1089

docs(prefer-expect-assertions): make correct code sample actually correct

---

package.json
yarn.lock

chore: update to Jest 28

---

src/rules/valid-expect.ts

Noticed this while working on #1173 - it's a completely duplicated check so might as well get rid of it

refactor(valid-expect): eliminate duplicate check

---

package.json

It's been a while since we've run this, and so there's a few new keys supported now.

chore: sort package.json

---

src/rules/__tests__/max-expects.test.ts
src/rules/max-expects.ts

fix(max-expects): don't count `expect.<member>()` calls towards max

---

package.json
src/rules/unbound-method.ts
yarn.lock

Plugin doesn't report them anymore

chore: rollback eslint-plugin-eslint-plugin

---

README.md

docs: reference `eslint-plugin-jest-extended` in README

---

src/rules/__tests__/max-expects.test.ts
src/rules/max-expects.ts

fix(max-expect): reset `expect` counter when entering and exiting test function calls

---

.github/workflows/nodejs.yml
package.json
yarn.lock

feat: drop support for `eslint@6`

---

src/rules/__tests__/prefer-equality-matcher.test.ts
yarn.lock

@G-Rath getting a type error from https://github.com/jest-community/eslint-plugin-jest/blob/966fe5c4a976b24dce46be2563ec719a61439bb2/src/rules/__tests__/prefer-equality-matcher.test.ts#L12-L19

chore: update ts-eslint

---

tsconfig.json

chore: make sure that tools are typechecked

---

eslint-remote-tester.config.ts
package.json
tsconfig.json
yarn.lock

Resolves #1243
I'll sort out `dangerfile.ts` another time

ci: typecheck `eslint-remote-tester` config

---

src/rules/__tests__/prefer-spy-on.test.ts
src/rules/prefer-spy-on.ts

fix(prefer-spy-on): improve autofix

---

.github/workflows/nodejs.yml
package.json

https://github.blog/2023-04-19-introducing-npm-package-provenance/

chore: enable npm provenance

---

package.json
tsconfig.json
yarn.lock

chore: upgrade @tsconfig/node14

---

docs/rules/no-conditional-expect.md
yarn.lock

chore: update prettier

---

.eslintrc.js
src/rules/expect-expect.ts
src/rules/no-test-return-statement.ts
src/rules/no-untyped-mock-factory.ts
src/rules/prefer-spy-on.ts

~We're already doing this everywhere, might as well enforce it~

chore: enforce curly braces

---

src/rules/max-nested-describe.ts

refactor(max-nested-describe): simplify implementation

---

src/rules/__tests__/unbound-method.test.ts

https://github.com/typescript-eslint/typescript-eslint/issues/8232

chore: remove syntax error from test

---

.github/workflows/nodejs.yml
package.json
yarn.lock

feat: drop support for ESLint v7

---

README.md
docs/rules/no-done-callback.md
docs/rules/no-focused-tests.md
docs/rules/prefer-equality-matcher.md
docs/rules/prefer-expect-assertions.md
docs/rules/prefer-strict-equal.md
docs/rules/unbound-method.md

I dunno how `main` isn't failing, but here we are 😀 New link looks more user facing, so 👍

chore: regenerate docs

---

.husky/commit-msg
.husky/pre-commit
package.json
yarn.lock

https://github.com/typicode/husky/releases/tag/v9.0.1

chore: update husky

---

.github/workflows/nodejs.yml
package.json

feat: drop support for Node v14

---

package.json
tsconfig.json
yarn.lock

I forgot about this when doing #1527

chore: update TSConfig to use Node v16 defaults

---

src/rules/__tests__/no-conditional-expect.test.ts
src/rules/__tests__/no-conditional-in-test.test.ts
src/rules/__tests__/prefer-each.test.ts
src/rules/__tests__/prefer-hooks-in-order.test.ts
src/rules/__tests__/prefer-snapshot-hint.test.ts
src/rules/__tests__/require-hook.test.ts
src/rules/__tests__/valid-expect-in-promise.test.ts
src/rules/utils/__tests__/detectJestVersion.test.ts
src/rules/utils/__tests__/parseJestFnCall.test.ts

Spotted these while doing other stuff

test: remove some trailing whitespace

---

.github/workflows/nodejs.yml

ci: test against Node 22

---

src/rules/prefer-lowercase-title.ts

Credit to @y-hsgw for finding this over in #1573

refactor(prefer-lowercase-title): remove unneeded cast

---

.eslintrc.js

I finally tracked down this option 😅

ci: don't warn on unsupported typescript versions

---

.eslintrc.js

I meant to do this a while ago but forgot - there's no point in having these warn as no one actually notices them

chore: change warning rules to error

---

.github/workflows/nodejs.yml

Time to add this to the matrix

ci: test against Node v24

---

src/rules/__tests__/prefer-importing-jest-globals.test.ts

chore: remove addressed todo comment

---

CHANGELOG.md

docs: remove duplicate changelog entry (again)

---

.eslint-doc-generatorrc.js
.eslintrc.js
babel.config.js
tsconfig.json

We might as well check these files too

chore: run typechecking on js files
