rules/__tests__/prefer_to_have_length.test.js
rules/prefer_to_have_length.js

Fix to-have-length when there are no argument properties

---

.eslintrc.js
CHANGELOG.md
README.md
docs/rules/no-large-snapshots.md
index.js
package.json
processors/__tests__/snapshot-processor.test.js
processors/snapshot-processor.js
rules/__tests__/__snapshots__/no_large_snapshots.test.js.snap
rules/__tests__/no_large_snapshots.test.js
rules/no_large_snapshots.js

Implements `no-large-snapshots` rule as discussed in issue #21. This rule serves to discourage having large snapshots which are difficult to review and can lead to bugs being snuck in.
I added it to the `recommended` config as a `warn` and kept the default max of 50 lines threshold. I can modify this as needed though if you all would like.

Adds no-large-snapshots rule

---

rules/__tests__/prefer_to_be_null.test.js
rules/__tests__/prefer_to_be_undefined.test.js
rules/prefer_to_be_null.js
rules/prefer_to_be_undefined.js
rules/util.js

I've ran the plugin with all rules enabled over the jest code base. Found a false positive, but with this change, it looks pretty great 🙂 
`expect(something).to{Be,Equal}(somethingElse)` were the false positives. The other assertions were added as precautions as I broke all of them while fixing the first one.
/cc @xfumihiro

fix: support identifiers in to-be-undefined

---

.travis.yml
package.json
yarn.lock

Since we use `--ignore-engines` when installing, this is now ok
Might even speed up the build a tiny bit.

chore(package): add semantic-release as a dev dependency

---

docs/rules/valid-expect.md
rules/__tests__/valid_expect.test.js
rules/valid_expect.js

We got an error previously as well, but with a misleading message (`"resolves" was not called.`).

fix(valid-expect): error on missing async matchers

---

.eslintrc.js
package.json
rules/prefer_to_be_null.js
rules/prefer_to_be_undefined.js
rules/prefer_to_have_length.js
yarn.lock

This PR adds [eslint-plugin-eslint-plugin](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin) and its recommended configuration to this project's ESLint configuration. It has some useful rules for ESLint plugin codebases.
When adding the recommended configuration, there were three reports of this codebase violating the [require-meta-fixable](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/master/docs/rules/require-meta-fixable.md) rule, which I have addressed in this PR.
In the future, I would like to include and fix the [require-meta-docs-url](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/master/docs/rules/require-meta-docs-url.md) rule as well, but I wanted to see if you were open to this addition to the codebase first.
It may be …

chore: add eslint-plugin-eslint-plugin

---

.travis.yml
dangerfile.js

Adds:
- Danger - fixes #7 
- A rule to check that a PR has a body
- A rule to check that changes to `rules/*` includes a CHANGELOG entry
- A CHANGELOG - fixes #3

Add danger

---

.eslintrc.js
rules/util.js
rules/valid-expect-in-promise.js

https://eslint.org/docs/rules/eqeqeq
Thoughts on enabling this rule? I think it's a good practice, since `==` can lead to some unexpected behavior (some examples in the link above).

style(lint): enable eqeqeq rule

---

.eslintrc.js
dangerfile.js
package.json
yarn.lock

Related:
* https://github.com/jest-community/eslint-plugin-jest/pull/64#discussion_r167413883
* https://github.com/jest-community/eslint-plugin-jest/pull/56#discussion_r167414256
Enabling this rule should help prevent object destructuring errors on Travis CI for Node 4.

style(lint): enable node/no-unsupported-features rule

---

.eslintrc.js
rules/consistent-test-it.js
rules/lowercase-name.js
rules/no-disabled-tests.js
rules/no-focused-tests.js
rules/no-hooks.js
rules/no-identical-title.js
rules/no-large-snapshots.js
rules/no-test-prefixes.js
rules/prefer-expect-assertions.js
rules/prefer-to-be-null.js
rules/prefer-to-be-undefined.js
rules/prefer-to-have-length.js
rules/util.js
rules/valid-describe.js
rules/valid-expect-in-promise.js
rules/valid-expect.js

This adds a utility function and uses the version present in package.json for generating the URL to tagged version of the rule documentation. I think this is good because the documentation will match the version the user has installed. This way, even if a rule is changed or removed in the future, the user can find the documentation with ease.
Note: The rule `eslint-plugin/require-meta-docs-url` cannot be used with a function which would return the URL(see [not-an-aardvark/eslint-plugin-eslint-plugin#58](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/issues/58)) so I have disabled it.

docs: Use link to tagged version for rule docs

---

rules/consistent-test-it.js
rules/lowercase-name.js
rules/no-disabled-tests.js
rules/no-focused-tests.js
rules/no-hooks.js
rules/no-identical-title.js
rules/no-large-snapshots.js
rules/no-test-prefixes.js
rules/prefer-expect-assertions.js
rules/prefer-to-be-null.js
rules/prefer-to-be-undefined.js
rules/prefer-to-have-length.js
rules/util.js
rules/valid-describe.js
rules/valid-expect-in-promise.js
rules/valid-expect.js

- Use `__filename` to determine the rule name and build the docs link. This also fixes an inadvertent bug where the URL ended with `.md.md`(ex: `https://github.com/jest-community/eslint-plugin-jest/blob/v0.0.0-development/docs/rules/valid-expect.md.md` for `valid-expect`).
- Check the docs file exists and throw an error otherwise.

docs: Improve docs URL resolution

---

.eslintrc.js
rules/lowercase-name.js
rules/no-disabled-tests.js
rules/no-large-snapshots.js
rules/no-test-prefixes.js
rules/util.js
rules/valid-describe.js

This enables eslint rules `prefer-template` and `object-shorthand`. This improves readability, _in my opinion_ so I can understand if you do not want to merge it in.

style: tweak eslint config

---

.travis.yml
package.json
yarn.lock

I've been learning more about Jest runners this week and am opening this PR to see if you are 👍 / 👎  on adding [jest-runner-eslint](https://github.com/jest-community/jest-runner-eslint) as a Jest runner for this project.
Sample output of `yarn test`:
Running `yarn test` takes slightly longer, but it comes with the added benefit of being able to see lint and test failures all from within the Jest UI.
Another thing I noticed is that our tests look like this:
```js
const RuleTester = require('eslint').RuleTester;
const rules = require('../..').rules;
const ruleTester = new RuleTester();
ruleTester.run('valid-expect', rules['valid-expect'], {
valid: [/* ... */],
invalid: [/* ... */],
});
```
Since we require `rules` from `index.js` and access the rule itself by calling `rule['rule-name']`, …

chore: add jest-runner-eslint

---

rules/__tests__/consistent-test-it.test.js
rules/__tests__/lowercase-name.test.js
rules/__tests__/no-disabled-tests.test.js
rules/__tests__/no-focused-tests.test.js
rules/__tests__/no-hooks.test.js
rules/__tests__/no-identical-title.test.js
rules/__tests__/no-test-prefixes.test.js
rules/__tests__/prefer-expect-assertions.test.js
rules/__tests__/prefer-to-be-null.test.js
rules/__tests__/prefer-to-be-undefined.test.js
rules/__tests__/prefer-to-have-length.test.js
rules/__tests__/valid-describe.test.js
rules/__tests__/valid-expect-in-promise.test.js
rules/__tests__/valid-expect.test.js

This is a follow-up to the PR comment in #82 and https://github.com/jest-community/eslint-plugin-jest/pull/82#issuecomment-366438570.
The goal of this PR is that moving forward, when you modify one rule and run `yarn test --watch`, the Jest test runner will only test and lint the modified file instead of all rules (since we were previously requiring all rules in each test).

refactor: require rule file in tests

---

docs/rules/no-jest-import.md
index.js
rules/__tests__/no-jest-import.test.js
rules/no-jest-import.js

Closes #90.
Adds the eslint rule 'no-jest-import', disallowing any import from Jest.
Adds tests and documentation for rule.

feat: adds no jest import rule

---

rules/__tests__/valid-describe.test.js
rules/valid-describe.js

fix(valid-describe): add check for empty arguments

---

rules/__tests__/no-identical-title.test.js
rules/no-identical-title.js

This is a PR to improve the error message of `no-identical-title` rule, after the issue #107

fix(rules): improve no-identical-title error message

---

rules/__tests__/valid-describe.test.js
rules/valid-describe.js

Fixes #105.
I've added a new condition for an arrow function with concise body. I'm not good at writing English, so the report message may not be look good to you. If so, please let me know and I'll fix it!

fix(valid-describe): add check for concise body arrow functions

---

docs/rules/no-jasmine-globals.md
index.js
rules/__tests__/no-jasmine-globals.test.js
rules/no-jasmine-globals.js

In preparation for jest-circus, warning users about Jasmine usage would be great.
Will probably add to recommended in next major (whenever eslint 5 comes out)
/cc @captbaritone

feat(rules): add `no-jasmine-globals`

---

README.md
docs/rules/consistent-test-it.md
docs/rules/lowercase-name.md
docs/rules/no-disabled-tests.md
docs/rules/no-hooks.md
docs/rules/no-test-prefixes.md
docs/rules/prefer-expect-assertions.md
docs/rules/valid-describe.md
docs/rules/valid-expect-in-promise.md
package.json
yarn.lock

https://prettier.io/blog/2018/05/23/1.13.0.html
This PR updates to the latest version of Prettier. I also ran `npx prettier '**/*.{md,js,json}' --write` to format all files using this new version of Prettier, if you are open to that change. Looks like the only changes are `package.json` formatting and changing `*` to `-` for Markdown lists, which are detailed in the [release blog post](https://prettier.io/blog/2018/05/23/1.13.0.html).

chore(package): update to prettier@1.13.0

---

README.md

This PR converts the README's Rules table from inline- to reference-style links, which narrows the width of the table and (in my opinion) makes it easier to read and modify. Thoughts on this change?

docs: clean up rules table links

---

README.md
docs/rules/prefer-inline-snapshots.md
index.js
rules/__tests__/prefer-inline-snapshots.test.js
rules/prefer-inline-snapshots.js

Implement the `prefer-inline-snapshots` rule. This rule serves to encourage interspersing snapshots inline in test file code over writing them to a separate `_snapshots_/*.snap` file.
The believe is that the snapshot test is easier to comprehend when it can be seen as a whole. This is especially convenient during code-reviews.

feat(rules): add prefer-inline-snapshots

---

README.md
docs/rules/no-test-return-statement.md
index.js
rules/__tests__/no-test-return-statement.test.js
rules/no-test-return-statement.js

Adds a rule for not returning inside of a test. Related issue in Jest: https://github.com/facebook/jest/issues/6516

feat(rules): add `no-test-return-statement`

---

README.md
index.js

The rule `expect-expect` was not included

Add `expect-expect` rule in list

---

rules/__tests__/__snapshots__/no-large-snapshots.test.js.snap
rules/__tests__/no-large-snapshots.test.js
rules/no-large-snapshots.js

**Problem:** Configuring the rule `jest/no-large-snapshots` with `[{ maxSize: 0 }]` sets the line limit to `50` instead of `0`.
**Solution:** Treat `0` as a requirement for no snapshot.

fix: no-large-snapshots to allow maxSize of 0

---

README.md
docs/rules/prefer-strict-equal.md
index.js
rules/__tests__/prefer-strict-equal.test.js
rules/prefer-strict-equal.js

Implement the `prefer-strict-equal` rule. This rule serves to encourage stricter equality checks on objects.
The believe is that imposing stricter equality results in safer tests.

feat(rules): add prefer-strict-equal

---

docs/rules/expect-expect.md
rules/__tests__/expect-expect.test.js
rules/expect-expect.js

This adds `assertFunctionNames: ['expect']` option to `expect-expect` rule.
**Note:** current [valid](https://github.com/jest-community/eslint-plugin-jest/pull/139/files#diff-9dafa5d3e48128b6016f7d6d4962171cR13)/[invalid](https://github.com/jest-community/eslint-plugin-jest/pull/139/files#diff-9dafa5d3e48128b6016f7d6d4962171cR33) tests are left untouched & passing.

feat(rule): add allow option to expect-expect rule

---

README.md
docs/rules/require-tothrow-message.md
index.js
rules/__tests__/require-tothrow-message.js
rules/require-tothrow-message.js
yarn.lock

This closes #154.
This rule checks if `toThrow` or `toThrowError` has a message.

Add new rule: require-tothrow-message

---

README.md
docs/rules/no-alias-methods.md
index.js
rules/__tests__/no-alias-methods.test.js
rules/no-alias-methods.js

This rule ensures that only the canonical method name from the Jest docs are used for methods, rather than their alias forms. This ensures consistency in codebases, and makes it easier to search for all occurrences of a method.

New rule: no-alias-methods

---

rules/__tests__/prefer-strict-equal.test.js
rules/prefer-strict-equal.js

Only run the rule `prefer-strict-equal` on `CallExpression`s where `expect` is used.

prefer-strict-equal: Only run if `expect` is used

---

rules/no-jest-import.js

ESLint visitor selectors support [ESQuery](https://github.com/estools/esquery) syntax, which is similar to a CSS style selector pattern. I'm opening this PR partly to show that it's capable to move some logic into these selectors (like `[callee.name="require"]`), but also to get some feedback if there is interest in introducing these into the codebase. Learned about them this weekend and wanted to share in the context of an ESLint plugin. 🤓 No worries on my end if this is merged or closed, more just want to start a discussion.

refactor(no-jest-import): use ESQuery syntax for selectors

---

rules/no-disabled-tests.js

Following up to #158, this PR refactors `no-disabled-tests` to use [ESQuery selector syntax](https://eslint.org/docs/developer-guide/selectors).
What do you think about these changes? Does this seem more maintainable / cleaner, or does this make things harder to follow? Open to feedback and not tied to this getting merged - curious what your thoughts are. 😄

refactor(no-disabled-tests): use ESQuery selector syntax

---

rules/prefer-expect-assertions.js

Related to #158 and #169, this PR migrates to use [selector syntax](https://eslint.org/docs/developer-guide/selectors). If this helps with readability and maintenance, let's merge it; otherwise, happy to close any PR that makes things more complicated. 👍

refactor(prefer-expect-assertions): use ESQuery selectors

---

rules/expect-expect.js

This PR refactors to use [selector syntax](https://eslint.org/docs/developer-guide/selectors). Open to feedback on if this is a helpful refactor! 😄 
Relates to #158, #169, #170

refactor(expect-expect): clean up and use ESQuery syntax

---

rules/__tests__/expect-expect.test.js
rules/expect-expect.js
rules/no-disabled-tests.js
rules/util.js

fix(expect-expect): support MemberExpressions in assertFunctionNames

---

README.md
docs/rules/prefer-to-contain.md
index.js
rules/__tests__/prefer-to-contain.test.js
rules/prefer-to-contain.js

chore: add prefer-to-contain rule

---

rules/__tests__/no-disabled-tests.test.js
rules/__tests__/prefer-expect-assertions.test.js
rules/no-disabled-tests.js
rules/prefer-expect-assertions.js

A bug in the regex means that this version picks up functions it shouldn't and warns that they don't have two arguments. For example, these lines in our codebase fail:
```
const dummyItem = itemBuilder({ // fails here
```
```
const showOutOfStockBadge = itemEntirelyOutOfStock(this.props.item);
```
Commit includes a test that was failing and the fix which is just to wrap brackets around the match in the regex.

fix(no-disabled-tests): stop picking up all funcs that start it/test

---

README.md
docs/rules/no-test-callback.md
index.js
rules/__tests__/no-test-callback.test.js
rules/no-test-callback.js

Using a `done` callback is old-school, all the cool kids should use Promises these days. Especially because of `async-await`. We might also want to remove `done` from a future version of Jest, and this is a nice start to make people migrate.
/cc @rubennorte, since we talked about something like this

feat(rules): add `no-test-callback` rule

---

README.md
docs/rules/prefer-spy-on.md
index.js
rules/__tests__/prefer-spy-on.test.js
rules/prefer-spy-on.js
rules/util.js

Feedback welcome, especially the docs and error message.
Closes #185

Add prefer-spy-on rule

---

rules/__tests__/no-alias-methods.test.js
rules/no-alias-methods.js

The autofix for `no-alias-methods` didn't catch everything it could've in our internal repo. Specifically `.resolves` & `.rejects` were missed.
This PR assumes that the full list of `methodNames` can be prefixed with `.resolves` and `.rejects`.
There may be other helpers I've overlooked that could be added here. For now, I erred on the side of caution.

Fix: no-alias-methods supports .resolves & .rejects

---

.travis.yml
package.json
yarn.lock

They require node 8, which makes it a bit of a pain to manage.
The diff here is essentially added `@semantic-release/changelog` in the middle of the default plugin configuration. No idea if it works 📿

chore: add changelog to repo

---

README.md
docs/rules/prefer-todo.md
index.js
rules/__tests__/prefer-todo.test.js
rules/prefer-todo.js
rules/util.js

Added prefer-todo rule as mentioned #217

feat(rules): add prefer-todo rule

---

rules/lowercase-name.js
rules/prefer-spy-on.js

This PR replaces usage of non standard fields `start`, `end` with `range`.
Properties `start`, `end` should not be used (they may be removed in feature)
currently those rules are crashing because of that if you decide to use ([@typescript-eslint/parser](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser)) 
see: https://eslint.org/docs/developer-guide/working-with-custom-parsers#all-nodes
fixes: https://github.com/typescript-eslint/typescript-eslint/issues/175

fix: use range instead of start/end properties

---

README.md
docs/rules/prefer-called-with.md
index.js
rules/__tests__/prefer-called-with.js
rules/prefer-called-with.js

Suggest using `toBeCalledWith()` or `toHaveBeenCalledWith()` instead of the forms without argument checking.
This is a rule I've been enforcing on an ad-hoc basis at work, and I think a better general suggestion than `toBeCalledTimes(1)` suggested in https://github.com/jest-community/eslint-plugin-jest/issues/109 for robust assertions.
Similar to [prefer-toHaveBeenCalledWith from eslint-plugin-jasmine](https://github.com/tlvince/eslint-plugin-jasmine/pull/134).
This rule has no opinion on which matcher alias should be used.

Add new prefer-called-with rule

---

rules/__tests__/no-identical-title.test.js
rules/no-identical-title.js
rules/util.js

Currently `jest/no-identical-title` only checks against regular strings. As a result, this wouldn't get reported:
```
describe('an odd case where identical titles are not reported', () => {
it(`this does not work as expected`, () => {
//  ...test code here
});
it(`this does not work as expected`, () => {
//  ...test code here
});
});
```
This ticket fixes that by testing against `TemplateLiteral` nodes, but will never report if that node is using string interpolation (ie: has expressions, `${}` inside it).
Resolves #232

fix(jest/no-identical-title): not reporting when using backticks

---

rules/__tests__/no-identical-title.test.js
rules/no-identical-title.js

Hey, since the recent release (with #237), two different template literals with no expressions will show a lint error. This happens because we try to get their value in a way that doesn't work for template literals and get `undefined` ([see here](https://github.com/jest-community/eslint-plugin-jest/blob/master/rules/no-identical-title.js#L71)).
This PR handles this use-case and adds a test to it (which would fail the last release).
Thanks 🙏

fix(jest/no-identical-title): don't show an error for different template literals

---

__tests__/rules.test.js
index.js

Ref https://github.com/jest-community/eslint-plugin-jest/pull/238#issuecomment-473419411

fix: make sure to export all available rules

---

README.md
__tests__/rules.test.js
docs/rules/no-mocks-import.md
index.js
rules/__tests__/no-mocks-import.test.js
rules/no-mocks-import.js

@thymikee You can [cross this off your todo list](https://github.com/facebook/jest/issues/7679#issuecomment-456560340) ;)
@SimenB requesting review :D
Alternative to using `path` would have been `/(\/|^)__mocks__(\/|$)/`, but I found this easier to read.
Potential config option would be `allowImportBetweenMocks` that disables the rule inside of mocks (IIRC ESLint can give you the path of the file being linted) so you can compose mocks, but I don't consider that to be a good pattern usually so I think you should eslint-disable if you really want to do that.
BREAKING CHANGE:
Add no-mocks-import to recommended rules

feat: add no-mocks-import rule

---

rules/__tests__/no-mocks-import.test.js
rules/no-mocks-import.js

Close #249 
Co-authored-by: Martin Zlámal <mrtnzlml@gmail.com>

fix(no-mocks-import): do not crash on dynamic `require`

---

README.md

Added the first link to the section, a link to the eslint-plugin-jest-formatting repo.
The `eslint-plugin-jest-formatting` project aims to provide formatting rules (auto-fixable where possible) to ensure consistency and readability in jest test suites.

Created a section for `Related Projects`

---

package.json

Maybe I'm missing something, but running build during `postInstall` doesn't seem to be the right way to go.
This PR moves it into `pretest` instead.
Fixes #263

Do not run `yarn build` during postinstall hook

---

package.json

fix: move @typescript-eslint/experimental-utils to dependencies

---

README.md
src/index.js

This pull request creates an "all" shareable configuration that enables all rules similar to [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react) among others. It is a useful starting point for beginners who want to see everything the plugin is capable of before enabling selected rules, and can also make custom configurations less verbose.
I haven't previously contributed to this repository before, so please let me know if I missed anything that should have been included!

feat(config): added shareable configuration plugin:jest/all

---

src/rules/lowercase-name.js
src/rules/no-alias-methods.js
src/rules/no-commented-out-tests.js
src/rules/no-disabled-tests.js
src/rules/no-empty-title.js
src/rules/no-focused-tests.js
src/rules/no-identical-title.js
src/rules/no-jasmine-globals.js
src/rules/no-jest-import.js
src/rules/no-large-snapshots.js
src/rules/no-mocks-import.js
src/rules/no-test-callback.js
src/rules/no-test-prefixes.js
src/rules/no-test-return-statement.js
src/rules/no-truthy-falsy.js
src/rules/prefer-called-with.js
src/rules/prefer-expect-assertions.js
src/rules/prefer-inline-snapshots.js
src/rules/prefer-spy-on.js
src/rules/prefer-strict-equal.js
src/rules/prefer-to-be-null.js
src/rules/prefer-to-be-undefined.js
src/rules/prefer-to-contain.js
src/rules/prefer-to-have-length.js
src/rules/prefer-todo.js
src/rules/require-tothrow-message.js
src/rules/valid-describe.js
src/rules/valid-expect-in-promise.js
src/rules/valid-expect.js

I noticed that two rules (`lowercase-name` and `no-large-snapshots`) were missing schemas for their config.
This adds those schemas. Also to be explicit, I also declared all rules with no config as explicitly exposing no config by adding `schema: []`.

fix: add missing schemas so rule config is properly validated

---

README.md
docs/rules/no-duplicate-hooks.md
src/__tests__/rules.test.js
src/rules/__tests__/no-duplicate-hooks.test.js
src/rules/no-duplicate-hooks.js
src/rules/no-focused-tests.js
src/rules/no-hooks.js
src/rules/util.js

New Rule - no-duplicate-hooks

---

README.md
docs/rules/no-if.md
src/__tests__/rules.test.js
src/rules/__tests__/no-if.js
src/rules/no-if.js
src/rules/util.js

If statements in tests is usually a bad idea. This PR prevents them.
Examples of **incorrect** code for this rule:
```js
it('foo', () => {
if ('bar') {
// an if statement here is invalid
// you are probably testing too much
}
});
it('foo', () => {
const bar = foo ? 'bar' : null;
});
```
Examples of **correct** code for this rule:
```js
it('foo', () => {
// only test the 'foo' case
});
it('bar', () => {
// test the 'bar' case separately
});
it('foo', () => {
function foo(bar) {
// nested functions are valid
return foo ? bar : null;
}
});
```

feat(rules): adds `no-if` rule

---

README.md
docs/rules/no-export.md
src/__tests__/rules.test.js
src/rules/__tests__/no-export.test.js
src/rules/no-export.js

I ran into this issue when we had a set of helper functions in 1 test file that
got exported directly from a `-test.js` file. The test that was importing this
file then executes both it's own tests as well as the tests in the imported
file. We started seeing phantom snapshots show up that we weren't able to find
the origin of until we finally tracked it down and realized that a test file was
exporting shared functions. We fixed this by moving those functions out into
seperate files, but that was the inspiration of this rule.
This rule aims to eliminate duplicate runs of tests by exporting things from
test files. If you import from a test file, then all the tests in that file will
be run in each imported instance, so bottom line, don't export from a test, but
instead move helper functions …

feat(no-export): new rule for no-export

---

docs/rules/require-tothrow-message.md
src/rules/__tests__/require-tothrow-message.test.js
src/rules/require-tothrow-message.js

This PR fixes `require-tothrow-message` to properly require messages for async functions that use `.rejects.toThrow(Error)`.

fix(require-tothrow-message): require throw messages on async functions

---

src/rules/__tests__/valid-describe.test.ts
src/rules/tsUtils.ts
src/rules/valid-describe.ts

chore: migrate valid-describe to ts

---

src/rules/__tests__/lowercase-name.test.ts
src/rules/lowercase-name.ts
src/rules/tsUtils.ts

Converts a couple of `isX` utility methods into their TS variants, so that it's easier to convert rules :)

ts-migration/convert-is-utils-fns

---

src/rules/__tests__/no-disabled-tests.test.ts
src/rules/__tests__/no-jasmine-globals.test.ts
src/rules/no-disabled-tests.ts
src/rules/no-jasmine-globals.ts
src/rules/tsUtils.ts
src/rules/util.js

This might cause issues with #310 but these three functions are the only ones from `tsUtils` that are required for about three or four rules, so getting these across the line will let me land those straight away :)

ts-migration/convert-some-utils-functions

---

docs/rules/valid-expect.md
src/index.js
src/rules/__tests__/no-alias-methods.test.js
src/rules/__tests__/no-truthy-falsy.test.js
src/rules/__tests__/prefer-called-with.test.js
src/rules/__tests__/prefer-strict-equal.test.js
src/rules/__tests__/prefer-to-contain.test.js
src/rules/__tests__/prefer-to-have-length.test.js
src/rules/__tests__/require-tothrow-message.test.js
src/rules/__tests__/valid-expect.test.js
src/rules/no-alias-methods.js
src/rules/no-truthy-falsy.js
src/rules/prefer-called-with.js
src/rules/prefer-to-contain.js
src/rules/prefer-to-have-length.js
src/rules/require-tothrow-message.js
src/rules/util.js
src/rules/valid-expect.js

Assert that async `expect`s are awaited or returned - Closes #54, #254

---

src/rules/lowercase-name.ts
src/rules/tsUtils.ts

I didn't type the guards correctly the first time - see [this comment](https://github.com/jest-community/eslint-plugin-jest/pull/314#discussion_r305560370) for some more info.
This is something that should be looked into at some point; in JS the type guards are implemented using `getNodeName`, which'll give you the following:
```
describe(); // describe
describe.only(); // describe.only
describe.only.each('') // describe.only.each
```
This is then checked using `#has` against a `Set`, which has since become an enum.
However the original `Set` contained both functions and function chains:
```
const describeAliases = new Set([
'describe',
'describe.only',
'describe.skip',
'fdescribe',
'xdescribe',
]);
```
I've retyped the guards so that they now match the actual runtime checks that are …

ts-migration/improve-guards

---

src/rules/no-if.js
src/rules/util.js

This changes the behaviour of the js guard functions (`isHook`, `isTestCase`, and `isDescribe`) to match the TS behaviour in #316 
Currently only `CallExpression`s whose entire member chain is described in the related `Set` are considered to be "X" (where "X" is a hook, test case, or describe depending on which `is<x>` method is called).
For example, this means that `describe.only.each` isn't considered a `describe` by `isDescribe`.
This PR changes that behaviour to just the first member in the chain for if they're in the related `Set`.
Neither behaviour is strictly right or wrong, but this behavioural change currently exists in the TS branch, and so a change has to happen somewhere.
The new behaviour doesn't cause any tests to fail (aside from in `no-if`, which has been fixed), so it …

adjust js guard behavior

---

src/rules/__tests__/no-test-callback.test.ts
src/rules/no-test-callback.ts

This is a bit of a tricky one, b/c it's got a bit of "hypothetical" nulls that I can't figure out how to reproduce in action.
As a result, coverage is currently failing, and I've stuck a "please file a github issue" throw as we could use that code to actually test those branches :joy:
We could eliminate at least one check by having `isFunction` narrow to `ArrowFunctionExpression` rather than `ArrowFunctionExpression | FunctionExpression`, as only the latter has `body` defined as being nullable (for reasons I can't figure out - anything I try either has a body or gets thrown out as a syntax error).
Personally, I think they might be typed like that for if you're constructing AST nodes? But I can't find anything solid explanation :/
The other alternative is to use `!`, but personally I'm not …

ts-migration/no-test-callbacks

---

README.md
docs/rules/no-try-expect.md
src/__tests__/rules.test.js
src/rules/__tests__/no-try-expect.test.js
src/rules/no-try-expect.js

This rule prevents the use of `expect` inside `catch` blocks.
The following patterns are warnings:
```js
it('foo', () => {
try {
foo(); // `foo` may be refactored to not throw exceptions, yet still appears to be tested here.
} catch (err) {
expect(err).toMatch(/foo error/);
}
});
it('bar', async () => {
try {
await foo();
} catch (err) {
expect(err).toMatch(/foo error/);
}
});
```
The following patterns are not warnings:
```js
it('foo', () => {
expect(() => foo()).toThrow(/foo error/);
});
it('bar', async () => {
await expect(fooPromise).rejects.toThrow(/foo error/);
});
```
Related https://github.com/jest-community/eslint-plugin-jest/issues/295

feat(rules): no-try-expect

---

src/rules/__tests__/no-identical-title.test.js
src/rules/util.js

This PR fixes #340 (well, only a part of it)
By improving the utilities `isTestCase` and `isDescribe` to return `true` only when used with valid properties (e.g. `test.skip`) in oppose to `test.foo` which is not a valid test case.

fix(util): identify only valid global properties

---

src/rules/tsUtils.ts
src/rules/util.js

This PR fixes #340 for TypeScript as well after implementing it on #341.
The types has reminded me that I've needed to verify that the property is an identifier before accessing its name, so I've changed it as well in the js `util`.

fix(tsutils): identify only valid global properties

---

src/rules/__tests__/no-empty-title.test.ts
src/rules/no-empty-title.ts
src/rules/tsUtils.ts

This PR converts the `no-empty-title` rule from JavaScript to TypeScript.

ts-migration/no-empty-title

---

src/rules/__tests__/no-try-expect.test.ts
src/rules/no-try-expect.ts
src/rules/tsUtils.ts

I had to alter the tests from using `catch` w/o a parameter.
For some reason it would cause a parsing error - I don't know if that's a TS or ESlint support problem, but since it's not critical to the rule (it just changes the `CatchClause#param` property from `Identifier` to `null`), I've omitted it for now.

ts-migration/no-try-expect

---

src/rules/__tests__/valid-expect.test.js
src/rules/valid-expect.js

valid-expect does not work with then - Closes #347

---

src/rules/__tests__/prefer-to-be-null.test.js
src/rules/__tests__/prefer-to-be-undefined.test.js
src/rules/util.js

Fixes #357 
It's a simple quick fix, as the underlying problem is fixed by the upcoming ts conversation stuff.

methodName: ensure method(node) returns truthy before trying to use return

---

.eslintrc.js
src/globals.json
src/index.js

I was happily surprised to find out that git can cherry-pick across file types :D

chore(index): move globals into json file

---

src/__tests__/rules.test.ts
src/index.ts

chore(index): convert to typescript.
Might as well break this out too :joy:

ts-migration/index

---

babel.config.js
package.json
src/__tests__/rules.test.ts
src/index.ts
yarn.lock

@SimenB I probably spent more time than I should, but hey least I know a lot more about babel :D
I'll make a PR into `jest` soon, once I've convinced my laptop to play nice (and once I've figured out how to install the package...).

Use export assignment

---

src/rules/no-empty-title.ts
src/rules/no-identical-title.ts
src/rules/tsUtils.ts

I was converting `no-large-snapshots`, as that pulls in all the `getAccessorValue` & related stuff w/o needing the expect parsing, when I realised that `no-empty-title` can be easily simplified :D

ts-migration/improve-no-empty-title

---

src/rules/no-mocks-import.ts
src/rules/tsUtils.ts

I can't remember what logic I used to justify `isLiteralNode` :joy:
```
export const isLiteralNode = (node: {	
type: AST_NODE_TYPES;	
}): node is TSESTree.Literal => node.type === AST_NODE_TYPES.Literal;
```

improve no-mocks-import

---

src/rules/no-identical-title.ts
src/rules/tsUtils.ts

This is based off #374, which should be reviewed & merged first.
I had to simplify `getAccessorValue` & `AccessorNode` to not handle `Identifier` nodes, as nothing covers that yet.
Otherwise it's a direct port.

Improve no identical title

---

src/rules/__tests__/no-large-snapshots.test.ts
src/rules/no-large-snapshots.ts
src/rules/tsUtils.ts
src/rules/util.js

ts-migration/no-large-snapshots

---

src/rules/__tests__/no-alias-methods.test.ts
src/rules/no-alias-methods.ts
src/rules/tsUtils.ts

`/* simenb ignore next it's that or radically restructure the types just to revert them in the next PR*/`

ts-migration/no-alias-methods

---

src/rules/prefer-strict-equal.ts
src/rules/tsUtils.ts

chore(prefer-strict-equal): use `parseExpectCall`

improve-prefer-strict-equal

---

src/rules/__tests__/prefer-spy-on.test.ts
src/rules/prefer-spy-on.ts

If this is expected behavior, I'd suggest removing the autofix when `mockImplementation` is empty because it can (and did in my case) break people's code.
Fixes: #389

fix(prefer-spy-on): do not change behavior of fixed instances

---

package.json
yarn.lock

Hopefully CI passes. Had to manually downgrade `inquirer` as they have dropped node 6 in a patch release

chore: upgrade to jest 24.9

---

src/rules/__tests__/prefer-to-be-null.test.ts
src/rules/__tests__/prefer-to-be-undefined.test.ts
src/rules/__tests__/prefer-to-contain.test.ts
src/rules/prefer-to-be-null.ts
src/rules/prefer-to-be-undefined.ts
src/rules/prefer-to-contain.ts
src/rules/utils.ts

I think our *default* stance on casts should be to just ignore them where possible, instead checking the node they're casting, for similar reason to why we don't bother w/ `Boolean(<value>)`
There could of course be code where it's logical to take casts into account, but I think this is a sensible default.
As such, I added `expect(a.includes(b)).toEqual(0 as boolean);` to reflect that.
fixes #332

Fix ts as expression type error

---

src/rules/prefer-to-contain.ts
src/rules/utils.ts

@SimenB I figured since you liked the original code so much, you'd enjoy some more.
Totally wasn't me forgetting to update the types in `prefer-to-contain` :joy:

chore(utils): improve `followTypeAssertionChain` typing

---

README.md
docs/rules/require-top-level-describe.md
src/__tests__/rules.test.ts
src/rules/__tests__/require-top-level-describe.test.ts
src/rules/require-top-level-describe.ts

This PR intends to add a new ESLint rule which enforces the user to add a top-level `describe` in their test files.
Closes #401

feat(rules): add require-top-level-describe rule

---

docs/rules/prefer-to-be-null.md
docs/rules/prefer-to-be-undefined.md
docs/rules/prefer-to-contain.md
docs/rules/prefer-to-have-length.md
src/rules/__tests__/prefer-to-be-null.test.ts
src/rules/__tests__/prefer-to-be-undefined.test.ts
src/rules/__tests__/prefer-to-contain.test.ts
src/rules/__tests__/prefer-to-have-length.test.ts
src/rules/utils.ts

This PR adds `toStrictEqual` as equality matcher. This fixes the following rules:
- `prefer-to-be-null`
- `prefer-to-be-undefined`
- `prefer-to-contain`
- `prefer-to-have-length`
The tests and documentation have also been updated.

feat(matcher): add toStrictEqual as equality matcher

---

docs/rules/prefer-to-be-null.md
docs/rules/prefer-to-be-undefined.md
docs/rules/prefer-to-contain.md
docs/rules/prefer-to-have-length.md

#412 introduced a few typing errors, this fixes them.

chore(docs): fix typing error in function name

---

README.md

This PR solves #415 
I also made changes outside the table to align the format of the description of `recommended` and `style` configuration.

chore(docs): add style to rules table in readme

---

src/rules/no-empty-title.ts
src/rules/no-focused-tests.ts
src/rules/no-standalone-expect.ts
src/rules/prefer-todo.ts

Using the enum values as much as possible means it's easier to track where we depend on the name of jest functions; in turn makes it easier for me to create parsers (among other things) 😄

Use enum values

---

src/rules/lowercase-name.ts
src/rules/no-hooks.ts

I'm assuming these were done when `includes` wasn't transpiled.
Makes things a bit smaller :)

Use includes instead of reduce

---

src/rules/prefer-strict-equal.ts
src/rules/utils.ts

Allows `EqualityMatcher` to be more strictly typed to a specifically named matcher.

Improve prefer strict equal

---

src/rules/no-commented-out-tests.ts

Super minor optimisations - `[xf]` is slightly faster than `x|f`, and lets us drop `()`, and `]` doesn't need to be escaped.
Saves us a few bytes all round.

chore(no-commented-out-tests): remove unneeded escape and improve regex

---

src/rules/no-test-prefixes.ts
src/rules/valid-expect-in-promise.ts
tsconfig.json

I always forget this isn't enabled by `strict`.
I also enabled `forceConsistentCasingInFileNames` as it's a nice to have, and moved `moduleResolution` to be under `module` b/c of a very valid reason that's sadly classified.

Enable `noImplicitReturns`

---

README.md
docs/rules/prefer-hooks-on-top.md
src/__tests__/rules.test.ts
src/rules/__tests__/prefer-hooks-on-top.test.ts
src/rules/prefer-hooks-on-top.ts

Fixes #356 
Approach is to maintain a stack of `boolean` which gets marked as `true` when a hook is not before a test
Also an edge case
```js
describe("foo" () => {
beforeEach(() => {
//some hook code
});
// Not affected by rule
someSetup();
afterEach(() => {
//some hook code
});
test("bar" () => {
some_fn();
});
});
```

feat(rules): prefer-hooks-on-top

---

docs/rules/lowercase-name.md
src/rules/__tests__/lowercase-name.test.ts
src/rules/lowercase-name.ts

This makes things a bit nicer for writing tests for `supertest`.
When I finally get time to finish off my test prefix rule, it might be worth merging into that, but that'd require the whole rule to be merged in.

feat: support `allow` option in `lowercase-name` rule

---

docs/rules/valid-title.md
src/__tests__/rules.test.ts
src/rules/__tests__/valid-title.test.ts
src/rules/valid-title.ts

As part of this, added a valid-title rule which checks for accidental space and duplicate prefix
@G-Rath Kindly review the PR and let me know if there are any changes

feat(rules): prefer-valid-title (#273)

---

README.md
docs/rules/valid-title.md

Adds it to README and fixes copy-paste issue with `valid-title` docs.

docs: fix `valid-title` documentation

---

src/rules/__tests__/valid-title.test.ts
src/rules/valid-title.ts

fix:(valid-title): check if node has arguments first

---

src/rules/no-identical-title.ts
src/rules/utils.ts

For some reason I had `isTemplateLiteral` only check if a literal was "simple" if we were checking for a specific string.
While in theory it makes sense, it also doesn't as we can't (/don't want to try to) process literals w/ expressions in them. This lets us remove a template literal related check from `no-identical-title`, and also fixes a failing test that resulted when merging `no-empty-title` w/ `valid-title` in `next`.
Also changed `no-identical-title` to use `getStringValue` instead of `getAccessorValue`, b/c it's the slightly more correct method to use and eliminates a redundant check that always get called.

Always check if template literal is complex

---

src/rules/__tests__/consistent-test-it.test.ts
src/rules/__tests__/expect-expect.test.ts
src/rules/__tests__/no-hooks.test.ts
src/rules/consistent-test-it.ts
src/rules/expect-expect.ts
src/rules/lowercase-name.ts
src/rules/no-commented-out-tests.ts
src/rules/no-hooks.ts

Removes most of our type casts, making things a bit nicer.
This will cause a merge conflict w/ #419

Improve types

---

src/rules/__tests__/valid-title.test.ts
src/rules/valid-title.ts

Turns out `eslint` doesn't provide a decent way to get the quote type that is being used for string literals, which is annoying.

Add fixers for valid title

---

docs/rules/valid-title.md
src/rules/__tests__/valid-title.test.ts
src/rules/valid-title.ts

feat(valid-title): support detecting & fixing trailing spaces in titles

---

.github/workflows/release.yml
package.json
yarn.lock

fixes #361
CI may ignore this PR until `next` is rebased on master. doesn't matter though as this just changes things for semantic-release, which only runs on master.
@G-Rath opening up a PR rather than pushing directly as you might be mid-rebase and I don't wanna mess that up

chore: generate changelog file as part of release

---

package.json
yarn.lock

the theory is that this'll work. when I'm bored at work next time I'll copy over all releases as well, but at least future releases _should_ auto-populate
fixes #361

chore: commit changelog after generating it

---

.github/workflows/lint.yml
package.json
yarn.lock

not sure why this wasn't caught before, but https://github.com/jest-community/eslint-plugin-jest/pull/456/checks?check_run_id=277248012 fails since a dependency of danger (`gitlab`) requires node 10. we _could_ just pass `--ignore-engines` to `yarn`, but I'd prefer not to. might need to do so if this doesn't work out, though
EDIT:

chore: remove explicit dependency on danger

---

src/rules/__tests__/valid-describe.test.ts
src/rules/__tests__/valid-title.test.ts
src/rules/utils.ts
src/rules/valid-describe.ts
src/rules/valid-title.ts

Better support valid each

---

src/rules/__tests__/prefer-todo.test.ts
src/rules/prefer-todo.ts

This has been around since I converted everything to TypeScript, so surprised no one hit it before (including myself).

fix(prefer-todo): ensure argument exists before trying to access it

---

src/rules/__tests__/no-test-callback.test.ts
src/rules/no-test-callback.ts

Fixes #466 
@SimenB could you check that the commit message is correct for triggering a new release?

fix(no-test-callback): don't provide fix for `async` functions

---

src/rules/utils.ts

In my own VSCode current version of forming url to a rule is [incorrect](https://github.com/jest-community/eslint-plugin-jest/blob/v23.0.3/docs/rules/prefer-expect-assertions.js.md). 
Because of after transformation from TypeScript to JavaScript all **.ts file extensions become **.js and hence the below statement is invalid now:
https://github.com/jest-community/eslint-plugin-jest/blob/b4868becf70e162aabcce14910d84947b48a83f8/src/rules/utils.ts#L14
I suggest version that is independent on an extension.

fix: get correct ruleName without specifying file extension

---

docs/rules/lowercase-name.md

Looking at the latest version of the plugin code, the exception option looks to be `allowedPrefixes` not `allow`.
`allowPrefixes` works well on my project whereas `allow` was not doing the job.
Keep up the good work! 🃏

docs(rules): expose the right options for exceptions option

---

.eslintrc.js
package.json
src/rules/__tests__/consistent-test-it.test.ts
src/rules/__tests__/expect-expect.test.ts
src/rules/__tests__/lowercase-name.test.ts
src/rules/__tests__/no-alias-methods.test.ts
src/rules/__tests__/no-duplicate-hooks.test.ts
src/rules/__tests__/no-hooks.test.ts
src/rules/__tests__/no-identical-title.test.ts
src/rules/__tests__/no-if.test.ts
src/rules/__tests__/no-jest-import.test.ts
src/rules/__tests__/no-mocks-import.test.ts
src/rules/__tests__/no-test-callback.test.ts
src/rules/__tests__/no-try-expect.test.ts
src/rules/__tests__/prefer-expect-assertions.test.ts
src/rules/__tests__/prefer-hooks-on-top.test.ts
src/rules/__tests__/prefer-spy-on.test.ts
src/rules/__tests__/require-to-throw-message.test.ts
src/rules/__tests__/valid-describe.test.ts
src/rules/__tests__/valid-expect-in-promise.test.ts
src/rules/__tests__/valid-expect.test.ts
src/rules/__tests__/valid-title.test.ts
src/rules/no-alias-methods.ts
src/rules/no-focused-tests.ts
src/rules/prefer-expect-assertions.ts
src/rules/require-to-throw-message.ts
src/rules/utils.ts
src/rules/valid-expect-in-promise.ts
yarn.lock

General house cleaning - removed some comments that are no longer needed, and chucked in `eslint-plugin-eslint-comments` b/c why not.
Also refactored `no-alias-methods` to use a map instead of an array, which is technically slightly faster, but also just generally nicer logic-wise.
Finally, fixed the message of `require-to-throw-message` to use the right data property :D
That also made me realise it could be a good candidate for the new suggestions api? provided it lets you take in user input.
@SimenB I adjusted the `eslint` config to use `eslint-config-prettier` - let me know if I've just refactored away a work around for something?

chore: minor housekeeping

---

.eslintrc.js

Turns out if you don't enable it, it won't work!

chore: enable `eslint-comments/no-unused-disable`

---

docs/rules/no-focused-tests.md
src/rules/__tests__/no-focused-tests.test.ts
src/rules/no-focused-tests.ts

[Jest allows to focus tests using `.each` with table format too](https://jestjs.io/docs/en/api#testonlyeachtable-name-fn) so this PR aims to include this variant in `no-focused-tests` rule.

feat(no-focused-tests): check focused tests using .each with table format

---

src/rules/__tests__/no-focused-tests.test.ts
src/rules/no-focused-tests.ts

Adjust no focused tests to support tables

---

docs/rules/valid-expect.md
src/rules/__tests__/valid-expect.test.ts
src/rules/valid-expect.ts

Makes the following an error under the `valid-expect` rule:
```js
await expect('something'); // No assertion was called on expect().
```
As this plugin already has a rule for `expect`-with-no-assertions, I thought I'd add a similar one for `await expect`.
Speaking from recent experience, the simple mistake of awaiting the wrong thing (`await expect('something')` instead of `await 'something'`) can be a pain to track down and fix, as its effects are likely to be felt far from the line containing the actual mistake (which itself will never throw at runtime).

feat(valid-expect): warn on `await expect()` with no assertions

---

src/rules/__tests__/consistent-test-it.test.ts
src/rules/__tests__/no-commented-out-tests.test.ts
src/rules/__tests__/no-disabled-tests.test.ts
src/rules/__tests__/no-focused-tests.test.ts
src/rules/__tests__/no-identical-title.test.ts
src/rules/__tests__/no-if.test.ts
src/rules/__tests__/no-standalone-expect.test.ts
src/rules/__tests__/no-test-prefixes.test.ts
src/rules/__tests__/no-try-expect.test.ts
src/rules/__tests__/prefer-todo.test.ts
src/rules/__tests__/valid-title.test.ts
src/rules/no-disabled-tests.ts
src/rules/no-focused-tests.ts
src/rules/no-if.ts
src/rules/utils.ts

Superseeds #498 and #432 (closes #498)
This is the final product of @leonardovillela's work - I merged a commit that made a conflict, and so I just resolved it locally and pushed it up :)
Hope you don't mind @leonardovillela - thanks for the PR!

feat(rules): add .concurrent support (#498)

---

src/rules/__tests__/expect-expect.test.ts
src/rules/__tests__/no-if.test.ts
src/rules/__tests__/no-test-return-statement.test.ts
src/rules/__tests__/no-try-expect.test.ts
src/rules/expect-expect.ts
src/rules/no-if.ts
src/rules/no-test-return-statement.ts
src/rules/no-try-expect.ts
src/rules/utils.ts

Add support for the following test file structure.
```js
test('my test', myTest)
function myTest() {
expect(true).toBe(true)
}
```
Methods that are directly referenced will be ananalyzed for the
following rules `expect-expect` `no-if` `no-test-return-statement`,
`no-try-expect`

feat(rules): add support for function declaration as test case

---

docs/rules/expect-expect.md
src/rules/__tests__/expect-expect.test.ts
src/rules/__tests__/no-jasmine-globals.test.ts
src/rules/utils.ts

Added support for chained assertion function names and method calls. (see also #471)
This makes it easy to support 3rd party assertion libraries like [SuperTest](https://www.npmjs.com/package/supertest) with the option `{ "assertFunctionNames": ["expect", "request.get.expect"] }`
Examples of **correct** code for deep assertion functions with the
`{ "assertFunctionNames": ["expect", "tester.foo.expect"] }` option:
```js
/* eslint jest/expect-expect: ["error", { "assertFunctionNames": ["expect", "tester.foo.expect"] }] */
test('nested expect method call', () => {
class Foo {
expect(k) {
return k;
}
}
let tester = {
foo: function() {
return new Foo();
},
};
tester.foo().expect(123);
});
```

feat(expect-expect): support chained function names (#471)

---

src/rules/__tests__/valid-expect.test.ts
src/rules/valid-expect.ts

Finally got around to refactoring the messages for `valid-expect`.
They're now written in nice active voice instead of passive, and I've merged a few of them so that they're consistent.
I don't think it's breaking, nor requires much of a review, but it's also not in any particular rush so I'll leave this open for a bit for folks to have a read over and comment on if they're happy or not.

feat(valid-expect): refactor `valid-expect` linting messages

---

docs/rules/expect-expect.md
package.json
src/rules/__tests__/expect-expect.test.ts
src/rules/expect-expect.ts
yarn.lock

Added support for glob patterns to specify assertion function names like `request.*.expect` (see
[micromatch](https://github.com/micromatch/micromatch) for syntax)
Implements #471
Examples of **correct** code for working with the HTTP assertions library
[SuperTest](https://www.npmjs.com/package/supertest) with the `{ "assertFunctionNames": ["expect", "request.*.expect"] }` option:
```js
/* eslint jest/expect-expect: ["error", { "assertFunctionNames": ["expect", "request.*.expect"] }] */
const request = require('supertest');
const express = require('express');
const app = express();
describe('GET /user', function() {
it('responds with json', function(done) {
request(app)
.get('/user')
.expect('Content-Type', /json/)
.expect(200, done);
});
});
```

feat(expect-expect): support glob patterns for assertFunctionNames (#471)

---

src/rules/__tests__/no-if.test.ts
src/rules/no-if.ts

@SimenB I think it might be worth refactoring this into `no-conditional-expect` at some point 🤔 
Looking over `no-try-expect`, I'm pretty sure they're doing almost the exact same thing - I'm going to look to reimplement one of these two rules so that they at least use the same style (one pushes booleans into an array, the other nodes, or something like that 🤷‍♂ )
Fixes #505

feat(no-if): support `switch` statements

---

.eslintrc.js
src/rules/__tests__/no-large-snapshots.test.ts
src/rules/no-commented-out-tests.ts
src/rules/no-export.ts
src/rules/valid-title.ts

It's meant to be better & safer :)

chore(lint): enable `require-unicode-regexp` rule

---

docs/rules/valid-title.md
src/rules/__tests__/valid-title.test.ts
src/rules/valid-title.ts

feat(valid-title): support `disallowedWords` option

---

docs/rules/expect-expect.md
package.json
src/rules/__tests__/expect-expect.test.ts
src/rules/expect-expect.ts
src/rules/utils.ts
yarn.lock

I've created a small utility function `nodeNameMatch` that can be used to match node names against a list of patterns.
Patterns can have single and double wildcards.
For example `request.get().bar().expectSomething(456)`
- `request.**.expectSomething` will pass
- `request.**.expect*` will pass
- `request.get.bar.expect*` will pass
- `request.*.expectSomething` will fail (you need to use `**` for multiple segments)
This removes the dependency on micromatch

chore(deps): removed dependency on micromatch for expect-expect

---

src/rules/utils.ts

Nothing major, but I realised two of the case returns were the same, and that it was duplicating the `AccessorNode` logic

chore: simplify `getNodeName`

---

src/rules/utils.ts

chore: fix parameter name typo

---

docs/rules/no-large-snapshots.md
src/rules/__tests__/no-large-snapshots.test.ts
src/rules/no-large-snapshots.ts

feat(no-large-snapshots): add setting to define maxSize by snapshot type

---

package.json

Discovered this while setting up `eslint-plugin-jest-extended` - turns out we're shipping a whole extra 8kb 😱😱😱
```
.
├── docs
│   └── rules
└── lib
├── __tests__
│   └── __snapshots__
├── processors
└── rules
7 directories
```
I've taken swift action to rectify this asap 🚓👮

fix: remove tests from published package

---

src/rules/__tests__/prefer-to-contain.test.ts
src/rules/prefer-to-contain.ts
yarn.lock

fix(prefer-to-contain): check that expect argument is defined before use

---

README.md
docs/rules/no-deprecated-functions.md
src/__tests__/__snapshots__/rules.test.ts.snap
src/__tests__/rules.test.ts
src/rules/__tests__/no-deprecated-functions.ts
src/rules/no-deprecated-functions.ts

I've done for the simple route - hopefully jest won't have any big deprecations, but if so we can refactor.
closes #559 
/cc @cpojer - this should do as a codemod, tho I'm curious on if Facebook have any `x["y"]` syntax in your codebase 🤔

feat: create `no-deprecated-functions`

---

README.md
docs/rules/no-deprecated-functions.md
package.json
src/rules/__tests__/no-deprecated-functions.test.ts
src/rules/no-deprecated-functions.ts
yarn.lock

This is pretty cool, if I do say so myself.
For now while it's implemented all as util functions, I've lumped them in `no-deprecated-functions` as `utils` is getting pretty big & I'd rather have this reviewed first since it's easy to move them out.
I've tested this locally against a few projects, including `@typescript-eslint`, and nothing went wrong.
fixes #561

feat(no-deprecated-functions): support jest `version` setting

---

.github/workflows/nodejs.yml

ci: run tests against `eslint@7`

---

README.md
docs/rules/no-restricted-matchers.md
src/__tests__/__snapshots__/rules.test.ts.snap
src/__tests__/rules.test.ts
src/rules/__tests__/no-restricted-matchers.test.ts
src/rules/no-restricted-matchers.ts

This rule lets us deprecate & drop at least the following:
* `no-truthy-falsy`
* `no-expect-resolves`
* `prefer-inline-snapshots`
In theory we could drop a few more, but I think they have their own context that makes them worth keeping:
* `prefer-called-with`: I've not come up with a nice syntax that lets you ban a matcher *unless* it has a modifier, so you could ban `toHaveBeenCalled` but that would also ban `not.toHaveBeenCalled`.
* `prefer-strict-equals`: while this can be handled by `ban-matchers`, I feel like this is one we want to recommend (so having its own rule gives it a name + specific documentation), and provide an autofix/suggestion for (more on this below)
* `no-alias-methods`: again as with the case of `prefer-strict-equals`, this has a fixer, and a history behind it.
This …

feat: create `no-restricted-matchers` rule

---

README.md
docs/rules/no-expect-resolves.md
docs/rules/no-truthy-falsy.md
docs/rules/prefer-inline-snapshots.md
src/rules/no-expect-resolves.ts
src/rules/no-truthy-falsy.ts
src/rules/prefer-inline-snapshots.ts

Deprecate rules

---

docs/rules/valid-expect.md
src/rules/__tests__/valid-expect.test.ts
src/rules/valid-expect.ts

closes #391
closes https://github.com/mattphillips/jest-expect-message/issues/6
related: https://github.com/mattphillips/jest-expect-message/issues/10

feat(valid-expect): support `minArgs` & `maxArgs` options

---

src/rules/__tests__/no-if.test.ts
src/rules/__tests__/no-test-return-statement.test.ts
src/rules/__tests__/require-top-level-describe.test.ts
src/rules/no-if.ts

Noticed this while working on `no-conditional-expect`, and figured it would be better as a bug release.
Also renamed the messageId to be different from the one used by `no-conditional-expect`.

Minor fixes

---

yarn.lock

Renovate seems to have stopped for some reason.
Included in this is `TypeScript` being updated so we can now use `// @ts-expect-error`, ~and `@typescript-eslint` so we can use the `suggestion` property.~

chore: refresh lock file

---

src/globals.json

This adds `fail` as a supported global.

fix: add `fail` to globals

---

src/rules/__tests__/no-deprecated-functions.test.ts

fixes #591
I'm really curious to why this only failed on Node 8 & 10 - my guess is that `Module.createRequire` behaviour works slightly differently than the fallback methods, but haven't tested that in full.

test: ensure `cwd` is restored after each test

---

.eslintignore
.eslintrc.js
package.json
src/__tests__/rules.test.ts
src/rules/__tests__/no-deprecated-functions.test.ts
src/rules/expect-expect.ts
src/rules/lowercase-name.ts
src/rules/no-alias-methods.ts
src/rules/no-duplicate-hooks.ts
src/rules/no-focused-tests.ts
src/rules/no-identical-title.ts
src/rules/no-jasmine-globals.ts
src/rules/no-large-snapshots.ts
src/rules/no-mocks-import.ts
src/rules/no-standalone-expect.ts
src/rules/no-test-return-statement.ts
src/rules/no-truthy-falsy.ts
src/rules/prefer-expect-assertions.ts
src/rules/prefer-hooks-on-top.ts
src/rules/prefer-to-contain.ts
src/rules/prefer-todo.ts
src/rules/require-top-level-describe.ts
src/rules/utils.ts
src/rules/valid-expect-in-promise.ts
src/rules/valid-expect.ts
yarn.lock

I made a new eslint plugin for linting config files to check they're invalid, and for use of deprecated rules.
There's actually a couple of commits, but wanting to test out github actions annotations.

chore: minor tidy up of code

---

.eslintrc.js
package.json
renovate.json
src/rules/__tests__/valid-title.test.ts
src/rules/no-deprecated-functions.ts
src/rules/prefer-expect-assertions.ts
src/rules/valid-title.ts
tsconfig.json

Does what it says in the title. Reduces the diff between `master` & `next` - the main ones I wanted were the eslint rules, `tsconfig` target change, and code restructures, but figured I'd bring a few things along just to reduce the diff further.

chore: backport non-breaking changes from next

---

docs/rules/no-standalone-expect.md
src/rules/__tests__/no-standalone-expect.test.ts
src/rules/no-standalone-expect.ts

closes #551
closes #354
I've attempted to make this rules implementation a bit nicer too, since it had a slowly growing `if` condition that I think at least reads a bit better now since it "flows" downwards a bit nicer (imo).
@SimenB would you object to adding `padding-line-between-statements` with the config used [here](https://github.com/ackama/eslint-config-ackama/blob/master/index.js#L128-L155)?
(it requires a newline to be before a `return`, and after assignment blocks i.e `const`).
I don't think we have any big offenders, but I find it makes things a lot more readable

feat(no-standalone-expect): support `additionalTestBlockFunctions`

---

README.md
docs/rules/no-conditional-expect.md
docs/rules/no-try-expect.md
src/__tests__/__snapshots__/rules.test.ts.snap
src/__tests__/rules.test.ts
src/rules/__tests__/no-conditional-expect.test.ts
src/rules/no-conditional-expect.ts
src/rules/no-try-expect.ts

Closes #482
I originally was playing around with actually not caring if the `expect` was in a test, since overall it doesn't really matter where the `expect` is, it's still best to not have it in a condition, which worked nicely except it would require more logic for handling early returns and early throws.
I think it's doable, but adds more complexity than needed right now, as it started heavily crossing into the territory of other rules like `no-test-return-statement`.

Create `no-conditional-expect` & deprecate `no-try-expect`

---

package.json
yarn.lock

`@typescript-eslint` provides much more accurate types for eslint (some of which are exported from `@types/eslint` directly), so overall we should always just use those types instead.
`jest-snapshot` brings in `@types/prettier`, which is why the import in `tools/generate-rules-table` doesn't error with tsc, but we should depend on it explicitly for safety.

Adjust types packages

---

docs/rules/lowercase-name.md
src/rules/__tests__/lowercase-name.test.ts
src/rules/lowercase-name.ts

closes #247
closes #428 
I think this should be the default in the next major, as it's a pretty common-case to have when testing classes.

feat(lowercase-name): support `ignoreTopLevelDescribe` option

---

package.json

I suspect most of these were legacy from when the project was Javascript?
It's small fry, but still each build + remove takes around ~3 seconds, which is done after every install because of `prepare` (which itself calls `build` & then `postbuild`, which is already called by `build`). `prepare` is also called as part of the publishing scripts, as well as `prepublishOnly`; and then finally we call it before running our tests via `pretest`, which just isn't needed because the tests are run against `src` not `lib`.
`prepack` is called before packing the project which is done as part of publishing when `npm pack` is called; this means you can also run `pack` locally to check what'll be included in the published pack (vs using `prepublishOnly`).

chore: replace scripts with single `prepack` script

---

src/index.ts
src/rules/expect-expect.ts
src/rules/no-alias-methods.ts
src/rules/no-commented-out-tests.ts
src/rules/no-disabled-tests.ts
src/rules/no-export.ts
src/rules/no-focused-tests.ts
src/rules/no-jasmine-globals.ts
src/rules/no-standalone-expect.ts
src/rules/no-test-callback.ts
src/rules/no-try-expect.ts
src/rules/valid-describe.ts
tools/generate-rules-table.ts

While we don't change the recommended ruleset often, this ensures we'll keep the right properties up to date.
Looking over our tests I think some might be a bit overkill - I don't mind per say, but am conscientious of how many places changes have to happen i.e snapshotting + updating the rule count constant.

chore: build recommended ruleset based on rules meta doc property

---

docs/rules/valid-title.md
src/rules/__tests__/valid-title.test.ts
src/rules/valid-title.ts

Closes #233
Closes #605
I implemented both `mustMatch` & `mustNotMatch` for the sake of completeness, since RegExp is not good at handling "not" matches.

feat(valid-title): support `mustMatch` & `mustNotMatch` options

---

src/rules/__tests__/no-large-snapshots.test.ts
src/rules/no-large-snapshots.ts

Turns out when I converted this rule to TypeScript, I dropped the actual comparator, which apparently no ones noticed 😅
Came across this while doing #624, as I realised we're accepting RegExp instances from `.eslintrc.js` which isn't strictly wrong, but I think it might be worth deprecating in favor of just always taking RegExp strings as that's easy and reduces the chance [of being broken by a minor version of ESLint](https://github.com/eslint/eslint/pull/13034).
~The migration would be that people just add `^` & `$` to the start and end of their strings respectively, and then add `.source` to their RegExps.~
Edit: actually because we're accepting RegExp instances, we're getting both the source and flags, so we could do this change without it being breaking as we'd just wrap the strings …

fix(no-large-snapshots): actually compare allowed name strings to name

---

docs/rules/no-large-snapshots.md
src/rules/__tests__/no-large-snapshots.test.ts
src/rules/no-large-snapshots.ts

I'd be happy to deprecate passing in RegExp instances at the same time if we want to simplify things. I don't use the rule myself so not sure how heavily the RegExp support is used.

feat(no-large-snapshots): deprecate `whitelistedSnapshots` for new name

---

src/rules/no-standalone-expect.ts

ESLint won't stop you from passing in `undefined`, and considers it a value that exists when checking if it should use the default value rules can set.
This actually should have been a TS error, but I believe the types for `@typescript-eslint` meant it didn't have the full picture? This in turn meant when upgrading in `next` we changed a test to not pass `undefined`, thus losing a point of coverage.
Programming is weird.

chore(no-standalone-expect): mark option as optional

---

src/rules/no-test-callback.ts
src/rules/no-test-return-statement.ts
src/rules/prefer-todo.ts
src/rules/valid-describe.ts
src/rules/valid-expect-in-promise.ts

chore: remove unneeded conditions

---

src/rules/prefer-to-have-length.ts
src/rules/require-to-throw-message.ts
src/rules/utils.ts
src/rules/valid-expect.ts

Spotted this while doing #637 - it's impossible to craft an AST tree where a Node is both an `ExpectMember` & does not have a parent.
Also found a few conditions that can be simplified using optional chaining 🎉

Remove unneeded checks

---

src/rules/__tests__/no-large-snapshots.test.ts
src/rules/no-large-snapshots.ts

BREAKING CHANGE
closes #370
closes #581
Refactored the check to be a bit simpler by using our utils; this made me realise that `parent` on matcher nodes can never be undefined, letting us simplify a few checks in a follow up PR 🎉

fix(no-large-snapshots): run on all files regardless of type

---

README.md
src/__tests__/__snapshots__/rules.test.ts.snap
src/rules/no-conditional-expect.ts
src/rules/no-deprecated-functions.ts
src/rules/no-interpolation-in-snapshots.ts
src/rules/no-jasmine-globals.ts
src/rules/valid-title.ts

Let the games begin! 🎉 
The following rules are not in the recommended:
consistent-test-it
lowercase-name
no-alias-methods*
no-duplicate-hooks
no-expect-resolves
no-hooks
no-if
no-large-snapshots
no-test-return-statement
no-truthy-falsy
prefer-called-with
prefer-expect-assertions
prefer-hooks-on-top
prefer-inline-snapshots
prefer-spy-on
prefer-strict-equal
prefer-to-be-null*
prefer-to-be-undefined*
prefer-to-contain*
prefer-to-have-length*
prefer-todo
require-top-level-describe
require-to-throw-message
valid-title
*: in `style` ruleset
I think we should have `valid-title` as a recommended.
I wouldn't mind having `prefer-strict-equal` as recommended too, but don't think it's as important.

Update recommended ruleset

---

package.json
src/rules/no-focused-tests.ts
yarn.lock

`no-focused-tests` could probably use a rewrite using the utils, but it works so 🤷

chore: upgrade to `typescript@4`

---

README.md
docs/rules/no-done-callback.md
src/rules/__tests__/no-done-callback.test.ts
src/rules/no-done-callback.ts

feat(no-done-callback): support hooks

---

README.md

Fixes #658
I've not included a similar note for `plugin: ["jest"]` because that's actually an ESLint feature: when you extend a config from a plugin it'll enable that plugin - it actually isn't needed in our configs.

docs(readme): add note about `jest/globals` being set by configs

---

src/rules/__tests__/no-if.test.ts
src/rules/no-if.ts

Fixes #670
@SimenB I've looked at the [original PR](https://github.com/jest-community/eslint-plugin-jest/pull/293) and there's no discussion around this, so I'm guessing it was working off the fact that you're meant to use arrow functions with jest?

fix(no-if): check both types of function expression

---

docs/rules/prefer-expect-assertions.md
src/rules/__tests__/prefer-expect-assertions.test.ts
src/rules/prefer-expect-assertions.ts

We would like to add this new option on the `prefer-expect-assertions` rule, so the rule only applies to `async` tests.
I hope this you like this idea. I'm open for suggestions.

feat(prefer-expect-assertions): support `onlyFunctionsWithAsyncKeyword ` option

---

.github/workflows/release.yml

I think this makes sense
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_run

chore: run release workflow when other workflows complete

---

.eslintrc.js
src/rules/__tests__/consistent-test-it.test.ts
src/rules/__tests__/lowercase-name.test.ts
src/rules/__tests__/no-alias-methods.test.ts
src/rules/__tests__/no-jasmine-globals.test.ts
src/rules/__tests__/no-large-snapshots.test.ts
src/rules/__tests__/no-test-prefixes.test.ts
src/rules/__tests__/prefer-inline-snapshots.test.ts
src/rules/__tests__/prefer-spy-on.test.ts
src/rules/__tests__/prefer-to-be-null.test.ts
src/rules/__tests__/prefer-to-be-undefined.test.ts
src/rules/__tests__/prefer-to-contain.test.ts
src/rules/__tests__/prefer-to-have-length.test.ts
src/rules/__tests__/prefer-todo.test.ts
src/rules/__tests__/valid-title.test.ts

I was going to enable other rules too I think, but then forgot what ones. Also I tried enabling some of the other `eslint-plugin` rules but turns out they only work with `module.exports`.

chore: enable `eslint-plugin/test-case-property-ordering` rule

---

src/rules/__tests__/consistent-test-it.test.ts
src/rules/__tests__/no-disabled-tests.test.ts
src/rules/__tests__/no-standalone-expect.test.ts
src/rules/__tests__/no-test-prefixes.test.ts
src/rules/consistent-test-it.ts
src/rules/no-disabled-tests.ts
src/rules/no-test-prefixes.ts
src/rules/utils.ts

`it.each` has [an unusual syntax](https://jestjs.io/docs/en/api#2--testeachtablename-fn-timeout-) which means `no-disabled-tests`, `no-test-prefixes`, and `consistent-test-it` don't work for it. 
This PR makes `it.each` work with those three rules

fix: improve support for it.each involving tagged template literals

---

src/rules/__tests__/no-done-callback.test.ts
src/rules/no-done-callback.ts

Closes #709
my recent PR #701 caused a false positive for `no-done-callback` when used with jest-each (sorry!)
`it.each` uses the first argument for options, and the second argument for the done callback.
This PR fixes the bug and adds test cases for it.each

fix(no-done-callback): fix regression with it.each

---

README.md

Currently there is no official renovate badge and the one used here was pointing to an example endpoint that got removed.

docs(readme): remove outdated renovate badge

---

src/rules/__tests__/no-commented-out-tests.test.ts
src/rules/__tests__/no-disabled-tests.test.ts
src/rules/__tests__/no-duplicate-hooks.test.ts
src/rules/__tests__/no-standalone-expect.test.ts
src/rules/__tests__/no-test-return-statement.test.ts
src/rules/__tests__/prefer-expect-assertions.test.ts
src/rules/__tests__/valid-expect-in-promise.test.ts
src/rules/__tests__/valid-expect.test.ts
src/rules/__tests__/valid-title.test.ts

The main one left is `no-identical-title`, which is pretty much entirely made up of `].join('\n')` style test cases 😭

chore: use `dedent` for most tests

---

src/rules/__tests__/lowercase-name.test.ts
src/rules/lowercase-name.ts
src/rules/utils.ts
src/rules/valid-describe.ts

Fixes #744 
I've taken the "throw code in the air and see where it settles after a few iterations" refactor method.
I think we could probably extract a helper for checking if a things an `.each`, but not going to try to build it until we've got more rules interacting with `.each`.
Will conflict with #745, so should be rebased before merging.

fix(lowercase-name): support `.each` methods

---

src/rules/require-top-level-describe.ts

fix(require-top-level-describe): import function that actually exists

---

src/rules/__tests__/consistent-test-it.test.ts
src/rules/__tests__/no-disabled-tests.test.ts
src/rules/__tests__/no-done-callback.test.ts
src/rules/__tests__/no-test-prefixes.test.ts
src/rules/consistent-test-it.ts
src/rules/no-disabled-tests.ts
src/rules/no-done-callback.ts
src/rules/no-test-prefixes.ts
src/rules/utils.ts

retrying #701, this time without the regression for `no-done-callback` 🙊
`no-done-callback` now works for jest-each's tagged-template syntax, but intentionally ignores it.each's table/array syntax because I have no idea how to handle [this edge case](https://github.com/jest-community/eslint-plugin-jest/issues/710#issuecomment-726081134).

fix: proper support for it.each 

---

.github/workflows/nodejs.yml
README.md
package.json

I'll rename the branch then land this

chore: use `main` as default branch

---

src/rules/__tests__/no-disabled-tests.test.ts
src/rules/no-disabled-tests.ts

The missing brackets means we're currently checking for `(^xit) OR (xtest$)`

fix(no-disabled-tests): adjust selector to match only test functions

---

src/rules/__tests__/no-test-prefixes.test.ts

#722 fixed the first half of #776 - this is just adding an explicit test case for this situation.
Fixes #776

test(no-test-prefixes): add case for `xdescribe.each`

---

src/rules/__tests__/no-disabled-tests.test.ts
src/rules/no-disabled-tests.ts

#722 makes this just a matter of adding the extra `case`s 🎉 
Relates to #776

fix(no-disabled-tests): support `describe.skip.each` & `xdescribe.each`

---

src/rules/__tests__/consistent-test-it.test.ts
src/rules/utils.ts

I think [this](https://github.com/jest-community/eslint-plugin-jest/pull/722) PR added false positive ESLing errors where `test` inside `describe.each` was actually thought to be `it` inside `describe.each`. (and the other way around) - see failing tests.
The bug exists on the last release (`24.1.7`) but was not present before.
The fix was in the `isDescribe` and `isTestCase` helpers, which ignored the `.each` version with templates.

fix(consistent-test-it): false positives inside describe.each

---

package.json
yarn.lock

Husky now doesn't handle checking if you're in CI, so we have to ourselves.
This prevented #782 from going out.

ci: don't run git hooks when in ci

---

src/rules/__tests__/valid-describe.test.ts
src/rules/valid-describe.ts

Due to [my previous fix](https://github.com/jest-community/eslint-plugin-jest/pull/782), now `valid-describe` has false positives 😆

fix(valid-describe): false positive with template describe.each

---

src/rules/__tests__/no-identical-title.test.ts
src/rules/no-identical-title.ts

fix(no-identical-titles): ignore .each template cases

---

README.md
src/rules/__tests__/no-focused-tests.test.ts
src/rules/no-focused-tests.ts

Already marked as fixable in the README.md

feat(no-focused-tests): make fixable

---

src/rules/__tests__/no-focused-tests.test.ts
src/rules/no-focused-tests.ts

Noticed this while working on a refactor of `no-disabled-tests`: #787 changed the location we report on to be the actual `only` property, but doesn't account for `concurrent.only` meaning we're currently reporting on `concurrent` for those cases.

fix(no-focused-tests): report on `skip` instead of `concurrent`

---

src/rules/__tests__/consistent-test-it.test.ts
src/rules/consistent-test-it.ts

fix(consistent-test-it): properly handle `describe.each`

---

src/rules/__tests__/no-duplicate-hooks.test.ts
src/rules/no-duplicate-hooks.ts

fix(no-duplicate-hooks): support `describe.each`

---

src/rules/__tests__/lowercase-name.test.ts
src/rules/__tests__/prefer-expect-assertions.test.ts
src/rules/lowercase-name.ts
src/rules/prefer-expect-assertions.ts
src/rules/utils.ts

Fixes #676
Issue was that we were using a specific selector, which couldn't account for `.each` - have refactored the rule to match using conditions instead like the rest of our rules.
Had to modify `isEachCall` in the process - technically it's got a slightly different behaviour as it's stricter, but this is actually what's being checked for in the refactored utils so when #792 is landed this method will be doing the right thing anyway. Plus this hasn't broken any tests so its fine 
(it did break TypeScript, which is why I had to make a change to `lowercase-name` - I'm pretty sure this is another instance of https://github.com/microsoft/TypeScript/issues/35953 but tbh I'm going to look to do a major refactor of our types once I've straighted out the `.each`-based stuff anyway, which'll …

fix(prefer-expect-assertions): support `.each`

---

src/rules/__tests__/no-identical-title.test.ts

Almost wish there was an `eslint` rule that could detect this :(

test(no-identical-title): use `dedent` instead of `join('\n')`

---

src/rules/__tests__/consistent-test-it.test.ts
src/rules/__tests__/lowercase-name.test.ts
src/rules/__tests__/no-conditional-expect.test.ts
src/rules/__tests__/no-export.test.ts
src/rules/__tests__/no-if.test.ts
src/rules/__tests__/no-test-return-statement.test.ts
src/rules/__tests__/prefer-hooks-on-top.test.ts
src/rules/__tests__/require-top-level-describe.test.ts
src/rules/__tests__/utils.test.ts
src/rules/__tests__/valid-title.test.ts
src/rules/consistent-test-it.ts
src/rules/lowercase-name.ts
src/rules/no-conditional-expect.ts
src/rules/no-done-callback.ts
src/rules/no-duplicate-hooks.ts
src/rules/no-export.ts
src/rules/no-identical-title.ts
src/rules/no-if.ts
src/rules/no-standalone-expect.ts
src/rules/no-test-prefixes.ts
src/rules/no-test-return-statement.ts
src/rules/no-try-expect.ts
src/rules/prefer-expect-assertions.ts
src/rules/prefer-hooks-on-top.ts
src/rules/prefer-todo.ts
src/rules/require-top-level-describe.ts
src/rules/utils.ts
src/rules/valid-title.ts

We've had a bit of flurry of activity in the last few weeks which has resulted in some of our technical debt coming to the surface, so this is (hopefully) the start of me addressing some of that.
There are two main goals with this refactor:
* we're consistent by only matching if the given `node` is a *call* i.e it'll result in `jest` doing "something"
* This is primarily important for `.each`, because of`.each()` - while that looks like a call (and technically is), it's not the "right" kind of call we're wanting to match with these methods.
* we're matching all possible variations both in terms of properties and accessor style (dot property & square brackets)
Because in a perfect world I'd like this to be the last time I have to think twice about this when using these methods, I've …

fix: support all variations of `describe`, `it`, & `test`

---

docs/rules/no-focused-tests.md
src/rules/__tests__/no-focused-tests.test.ts

There's no such prefixed method for `test`; only `fit` & `fdescribe`

docs(no-focused-tests): remove references to `ftest` method

---

src/rules/__tests__/valid-describe.test.ts
src/rules/utils.ts
src/rules/valid-describe.ts

This cherry-picks the change I made in #814 to have `valid-describe` use the new `isDescribeCall` util, thus giving it better support for `describe.each`.

fix(valid-describe): support using `each` with modifiers

---

docs/rules/expect-expect.md

Change the suggested rule config for jest/expect-expect when using supertest to use "request.**.expect" in the assertFunctionNames array rather than "request.*.expect". A supertest chained assertion may have more than one function call between `request(app)` and `.expect()`. Without this change the following would raise an error/warning:
```js
describe('Get All Items', () => {
it('/items/all returns json list of all items', () =>
request(app)
.get('/items/all')
.set('Accept', 'application/json')
.expect('Content-Type', /json/)
.expect(200),
)
})
```

docs(expect-expect): change suggested rule config

---

src/rules/__tests__/lowercase-name.test.ts
src/rules/__tests__/no-conditional-expect.test.ts
src/rules/__tests__/no-focused-tests.test.ts
src/rules/__tests__/no-if.test.ts
src/rules/__tests__/no-test-return-statement.test.ts
src/rules/__tests__/utils.test.ts
src/rules/consistent-test-it.ts
src/rules/lowercase-name.ts
src/rules/no-duplicate-hooks.ts
src/rules/no-focused-tests.ts
src/rules/no-if.ts
src/rules/no-standalone-expect.ts
src/rules/no-test-prefixes.ts
src/rules/prefer-expect-assertions.ts
src/rules/prefer-todo.ts
src/rules/require-top-level-describe.ts
src/rules/utils.ts
src/rules/valid-describe.ts
src/rules/valid-title.ts

Implements the change described [here](https://github.com/jest-community/eslint-plugin-jest/pull/792#issuecomment-803498682), so that `isDescribeCall` and `isTestCaseCall` now return `true` for the outer `CallExpression` in `.each()()` calls, meaning matched nodes are now consistent as it'll always be the top-most one.
This has let us shed a bunch of edge-case code across our rules and utils, and also made it easy to refactor `no-focused-tests` so that it's 1/3rd smaller 🎉 
Because of the mix of dependent and independent changes, I'm going to open this PR as a draft, and cherry pick some of the changes out into their own PRs.
Resolves #809
Resolves #810
Resolves #811

fix: improve handling of `.each` calls and with tagged literals

---

docs/rules/no-conditional-expect.md
src/rules/__tests__/no-conditional-expect.test.ts
src/rules/no-conditional-expect.ts

fix(no-conditional-expect): check for expects in `catch`s on promises

---

src/rules/__tests__/valid-expect.test.ts
src/rules/valid-expect.ts

fix(valid-expect): support async `expect` in ternary statements

---

.github/workflows/nodejs.yml

per https://github.com/jest-community/eslint-plugin-jest/pull/843#issuecomment-847754749
Have pulled out both `typecheck` & `prettier:check` as they don't need to be run on the matrices - also removed what I'm pretty sure is unneeded `fetch-depth: 0`

ci: make more efficient

---

README.md

Github has introduced the Copy Markdown functionality, so users can click the copy button to get the command in their clipboard.
Having the $ in front of the copied command means they can't use this feature.

chore(readme): remove `$` from install instructions

---

docs/rules/valid-describe.md
src/rules/__tests__/valid-describe.test.ts
src/rules/valid-describe.ts

Jest 27 will throw an error if a describe block returns a value ([changelog](https://github.com/facebook/jest/blob/master/CHANGELOG.md#2700), [test-case](https://replit.com/@jcfranco/jest-playground#test.js)). This PR updates `valid-describe` to report on these instances that would fail tests. 
If deemed useful, I could look at making this fixable in a follow-up PR.

fix(valid-describe): report on concise-body arrow functions

---

README.md
docs/rules/max-nested-describe.md
src/__tests__/__snapshots__/rules.test.ts.snap
src/__tests__/rules.test.ts
src/rules/__tests__/max-nested-describe.test.ts
src/rules/max-nested-describe.ts
src/rules/utils.ts

Resolves #362
The idea is the same as the above issue. I changed the rule name and options to something more consistent with the `max-nested-callbacks` rule.

feat: create max-nested-describe rule

---

.github/workflows/nodejs.yml

BREAKING CHANGE: Drop support for ESLint 5

fix: stop testing ESLint 5

---

src/index.ts
src/rules/no-done-callback.ts
src/rules/no-focused-tests.ts
src/rules/prefer-expect-assertions.ts
src/rules/prefer-strict-equal.ts
tools/regenerate-docs.ts

We can land this ahead of time to reduce the overhead a little.

fix: mark rules that suggest fixes with `hasSuggestion` for ESLint v8

---

docs/rules/valid-title.md

The `$` character is used to assert the end of the line and the examples show strings that start with a specific word for which the `^` character should be used.

Fix regex in mustMatch and mustNotMatch examples

---

src/index.ts
src/rules/no-done-callback.ts
src/rules/no-focused-tests.ts
src/rules/prefer-expect-assertions.ts
src/rules/prefer-strict-equal.ts
tools/regenerate-docs.ts

#898 has a typo 🙈 
https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0#suggestions

fix: use correct property `hasSuggestions` rather than `hasSuggestion`

---

.github/workflows/lint.yml
.github/workflows/nodejs.yml

- Set action versions to major
This will create less PRs to update their versions
- ~Set node version to 16~
---
Taken from #903

chore(ci): specify only majors for GH Actions

---

docs/rules/max-nested-describe.md
docs/rules/no-done-callback.md
docs/rules/no-standalone-expect.md
docs/rules/no-test-return-statement.md

Noticed these while doing other work.

docs: minor tweaks

---

src/rules/__tests__/valid-expect-in-promise.test.ts
src/rules/valid-expect-in-promise.ts

fix(valid-expect-in-promise): support `finally`

---

src/rules/__tests__/valid-expect-in-promise.test.ts
src/rules/valid-expect-in-promise.ts

Noticed this while working on #740; tbh during this I noticed how buggy this rule actually is - among other things, it doesn't actually properly check for `expect` so it will match stuff like `myClass.method()`.
I'm going to have a go at seeing if I can re-write some parts of it to try and weed out these bugs, but they're not going to be easy as there's a lot of ways we can have false positives or negatives.

fix(valid-expect-in-promise): support additional test functions

---

src/rules/__tests__/no-identical-title.test.ts
src/rules/no-identical-title.ts

@SimenB I think we should try and get this sorted before the next major too, as
it has been similarly disruptive to a small subset of users.
I'd be interested in your opinion on this - my understanding of the rule is that
it's trying to enforce this:
> "you should be able to differentiate between two tests by their title alone"
As the title should always be provided to reporters whereas other information
(like what line in code the test is on) isn't guaranteed, and so having titles
that are identical on the same nesting level makes it very hard to tell which is
what test in code.
This is easy to handle with static titles, but `.each` supports injecting values
into their static titles, making it harder to decide if a title is unique or not
since we cannot predict the final title(s).
I …

fix(no-identical-title): always consider `.each` titles unique

---

docs/rules/require-top-level-describe.md
src/rules/__tests__/require-top-level-describe.test.ts
src/rules/require-top-level-describe.ts

Resolves #598
The argument could be made that maybe this should be part of a more general "max-stuff" rule, but for now the logic is simple enough so happy to include it in this rule, since it's already checking for top-level describes anyway.

feat(require-top-level-describe): support enforcing max num of describes

---

docs/rules/valid-title.md
src/rules/__tests__/valid-title.test.ts
src/rules/valid-title.ts

I'm wondering if maybe we should drop support for taking a string in favor of always passing a tuple (with or without the second item), as it'd make things a bit lighter for us by making the usage more consistent (both in code and docs) 🤔
I think a good follow-up feature would be to support _multiple_ matchers, so that you can reduce the complexity of single regexps + have more specific messages (implementation wise, this'd be that we support taking in an array of `MatcherAndMessage` & change our logic to do iterate over each `MatcherAndMessage`).
Slightly annoyingly, we could _almost_ deprecate `lowercase-name` in favor of this rule since you could use `/[^A-Z]/u.source` except that would also apply to top-level describes.
Fixes #688

feat(valid-title): allow custom matcher messages

---

README.md
docs/rules/no-deprecated-functions.md
src/index.ts
src/rules/__tests__/detectJestVersion.test.ts
src/rules/__tests__/no-deprecated-functions.test.ts
src/rules/detectJestVersion.ts
src/rules/no-deprecated-functions.ts

Resolves #874
Resolves #886
Resolves #888
Would be good if people could test this locally on a few projects and in editors - I think it's fine, but want to make sure we've checked that it won't make any editors explode (as thats the primary reason for why this is here).

fix(no-deprecated-functions): remove `process.cwd` from resolve paths

---

README.md
docs/rules/prefer-to-be.md
src/__tests__/__snapshots__/rules.test.ts.snap
src/__tests__/rules.test.ts
src/rules/__tests__/prefer-to-be.test.ts
src/rules/prefer-to-be.ts
src/rules/utils.ts

An even better version of #821 (plus it doesn't flag `toBe` 🤦).
This deprecates `prefer-to-be-undefined` & `prefer-to-be-null`, as well as supporting `toBeDefined` (vs `toBeUndefined`). (@SimenB let me know if you're happy with this, or if you think they should stay as different rules)
Closes #821
Closes #801

feat: create `prefer-to-be` rule

---

README.md
docs/rules/prefer-expect-resolves.md
src/__tests__/__snapshots__/rules.test.ts.snap
src/__tests__/rules.test.ts
src/rules/__tests__/prefer-expect-resolves.test.ts
src/rules/prefer-expect-resolves.ts

Resolves #803
I'd love to have a fixer, but `jest` kept giving me this:
```
(node:5300) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
--> starting at object with constructor 'Node'
|     property 'callee' -> object with constructor 'Node'
--- property 'parent' closes the circle
at stringify (<anonymous>)
at writeChannelMessage (internal/child_process/serialization.js:117:20)
at process.target._send (internal/child_process.js:805:17)
at process.target.send (internal/child_process.js:703:19)
at reportSuccess (/c/Users/G-Rath/workspace/projects-oss/eslint-plugin-jest/node_modules/jest-worker/build/workers/processChild.js:67:11)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5300) UnhandledPromiseRejectionWarning: Unhandled …
```

feat: create `prefer-expect-resolves` rule

---

src/rules/__tests__/prefer-to-be.test.ts
src/rules/prefer-to-be.ts

fix(prefer-to-be): don't consider RegExp literals as `toBe`-able

---

src/rules/__tests__/lowercase-name.test.ts
src/rules/lowercase-name.ts

fix(lowercase-name): consider skip and only prefixes for ignores

---

package.json
yarn.lock

`jest/no-deprecated-functions` requires `jest` if a version isn't explicitly set in the config to automatically detect it from jest's `package.json` manifest file.
As `jest` isn't declared as a dependency of `eslint-plugin-jest`, stricter node linkers like pnp and pnpm throw errors when trying to run the rule.
I opted to add it as an optional peer dependency as some consumers may explicitly declare their jest version in their eslint config, may not be using this specific rule, or `eslint-plugin-jest` may be included in a shareable eslint config that runs on some packages that may not include jest tests.

fix(no-deprecated-functions): mark jest as an optional peer dependency

---

src/rules/__tests__/prefer-to-be.test.ts
src/rules/prefer-to-be.ts

fix(prefer-to-be): preserve `resolves` and `rejects` modifiers

---

docs/rules/require-hook.md
src/rules/__tests__/require-hook.test.ts
src/rules/require-hook.ts

Some testing libs provide methods which takes hook as an argument and should be executed outside of a hook. The greatest example is using [`enableAutoDestroyHook` from `@vue/test-utils` lib ](https://vue-test-utils.vuejs.org/api/#enableautodestroy-hook). 
By default `jest/require-hook` rule throws an error in such correct code
```js
import {
enableAutoDestroy,
resetAutoDestroyState,
mount
} from '@vue/test-utils'
import Foo from './Foo.vue'
// calls wrapper.destroy() after each test
enableAutoDestroy(afterEach)
// resets auto-destroy after suite completes
afterAll(resetAutoDestroyState)
describe('Foo', () => {
it('renders a div', () => {
const wrapper = mount(Foo)
expect(wrapper.contains('div')).toBe(true)
// no need to call wrapper.destroy() here
})
})
```
To deal with it you must ignore …

Adding optional settings to require-hook rule

---

.github/workflows/smoke-test.yml

Came across this when picking up work for `eslint-plugin-jest-dom` - seems like a pretty cool thing to have for us too.

ci: add smoke test workflow

---

src/rules/__tests__/prefer-to-be.test.ts
src/rules/prefer-to-be.ts

fix(prefer-to-be): support template literals

---

src/rules/__tests__/no-large-snapshots.test.ts
src/rules/no-large-snapshots.ts

fix(no-large-snapshots): only count size of template string for inline snapshots

---

docs/rules/prefer-hooks-on-top.md
src/rules/__tests__/prefer-hooks-on-top.test.ts
src/rules/prefer-hooks-on-top.ts

Noticed this rule was looking a little messy when looking into #992.
tbh this rule should probably be renamed to something like `prefer-hooks-before-tests`.

fix(prefer-hooks-on-top): improve message & docs

---

src/rules/__tests__/prefer-to-contain.test.ts
src/rules/prefer-to-contain.ts
src/rules/utils.ts

Pretty happy with this - while the "feature" itself isn't one I think we really need, implementing it wasn't too hard and it made me realise how to _greatly_ simplify the fixer so now we're getting support for square bracket accessors for free + no longer have a couple of theoretical throws 🎉 
Fixes #369

fix(prefer-to-contain): support square bracket accessors

---

src/rules/__tests__/prefer-to-have-length.test.ts
src/rules/prefer-to-have-length.ts

Same as #1009 - the win is less since the fixer was smaller, but still a good one; in particular lets us get rid of the theoretical 
"not null" assertion 🎉

fix(prefer-to-have-length): support square bracket accessors

---

.github/workflows/smoke-test.yml
eslint-remote-tester.config.js
eslint-remote-tester.config.ts
package.json
yarn.lock

ci: properly configure smoke test

---

src/rules/__tests__/prefer-lowercase-title.test.ts
src/rules/prefer-lowercase-title.ts

Noticed this while doing a general look over of our codebase 😅

fix(prefer-lowercase-title): ignore `it` and `test` separately

---

docs/rules/prefer-expect-assertions.md
src/rules/__tests__/prefer-expect-assertions.test.ts
src/rules/prefer-expect-assertions.ts

This only checks for native loops - while we could try and check for calls to methods with names like `forEach`, I realised it actually makes sense to just have a whole third option for if `expect` is in a callback since they represent the same sort of situation as with promises and would cover `forEach`, `reduce`, `map`, etc without as many edge-cases or false negatives.
I'll do a follow-up PR for that option.
Resolves #540

feat(prefer-expect-assertions): support requiring only if `expect` is used in a loop

---

docs/rules/prefer-expect-assertions.md
src/rules/__tests__/prefer-expect-assertions.test.ts
src/rules/prefer-expect-assertions.ts

feat(prefer-expect-assertions): support requiring only if `expect` is used in a callback

---

README.md
docs/rules/prefer-comparison-matcher.md
src/__tests__/__snapshots__/rules.test.ts.snap
src/__tests__/rules.test.ts
src/rules/__tests__/prefer-comparison-matcher.test.ts
src/rules/prefer-comparison-matcher.ts

As documented, I decided to ignore the fact that you can use the comparison operators with strings but not with the jest matchers because I really don't think there's a good & common-enough use case for doing that (maybe aside from checking string sorting?) that makes it worth giving up being able to autofix.
Am open to PRs if someone wanted to have an option like `assumeVariablesHoldNumbers` that can be set to `false` to make this rule give suggestions instead of autofix, but for now have left that out.
I've also made this not do anything with the equality operators, as I'm making that into its own rule since that will have to use suggestions and is a little more complicated in terms of there being three possible operators.
Finally, this rule doesn't enforce one specific matcher in …

feat: create `prefer-comparison-matcher` rule

---

README.md
docs/rules/prefer-equality-matcher.md
src/__tests__/__snapshots__/rules.test.ts.snap
src/__tests__/rules.test.ts
src/rules/__tests__/prefer-equality-matcher.test.ts
src/rules/prefer-equality-matcher.ts

This introduces a rule similar to #1015 that checks for use of the strict equality operators and suggests using built-in matchers instead.
I'm expecting to do some code cleanup later since we've getting a few rules that share common functions, so for now it's straightforward but a bit WET.
This is expected to compliment rules like `prefer-strict-equal` & `prefer-to-be` which will handle sorting out the more specific matcher to use.

feat: create `prefer-equality-matcher` rule

---

docs/rules/valid-expect.md
src/rules/__tests__/valid-expect.test.ts
src/rules/valid-expect.ts

Have made the default the matchers from `jest-extended`, as I that's a pretty reasonable thing to do.
Fixes #488

feat(valid-expect): support `asyncMatchers` option and default to `jest-extended` matchers

---

package.json
yarn.lock

We need to force npm to be on v7 due to some change they've made which uses wildcards for all dependencies, leading to pulling in incompatible versions in yarn since they don't respect `bundleDependencies`.
I've reported this to yarn (discord, so no link), and I think they're gonna fix it 🙂 But this fixes a "vulnerability" (which, as always, is complete bullshit, but it is what it is)

chore: update semantic-release

---

README.md
docs/rules/no-conditional-in-test.md
src/__tests__/__snapshots__/rules.test.ts.snap
src/__tests__/rules.test.ts
src/rules/__tests__/no-conditional-in-test.test.ts
src/rules/no-conditional-in-test.ts

This replace is meant to replace `no-if`: in addition to making the name and documentation consistent (since the rule supports more than just `if` statements), it greatly simplifies it by reporting _any_ condition in a test state.
If developers have a good reason for a condition within a test, then they can disable the rule with an inline disable.
This fixes #1026
I'll do a follow-up PR deprecating `no-if`, so that there's a changelog entry for visibility.

feat: create `no-conditional-in-test` rule

---

README.md
docs/rules/no-if.md
src/__tests__/__snapshots__/rules.test.ts.snap
src/rules/no-if.ts

feat: deprecate `no-if` in favor of `no-conditional-in-test`

---

README.md
docs/rules/prefer-snapshot-hint.md
src/__tests__/__snapshots__/rules.test.ts.snap
src/__tests__/rules.test.ts
src/rules/__tests__/prefer-snapshot-hint.test.ts
src/rules/prefer-snapshot-hint.ts

* I've gone with `hint` instead of `name` as that's what the argument is called in the docs - however the docs do refer to it in a few places as "snapshot name" and it is used as part of the name. @SimenB imo it would be good to be consistent, so would be good if you could weigh in on if you'd prefer `hint` or `name` and I can do the legwork of making a PR to `jest` updating the docs and argument(s) to match
* I've not implemented the `never` option because I really don't think that is something people should be doing since there's no gain in not having a hint.
* I've set `multi` as the default because I think that is reasonable to assume the test title has enough context for one external snapshot matcher, but as soon as you have multiple in a single test you can't tell what each snapshot …

feat: create `prefer-snapshot-hint` rule

---

src/rules/__tests__/prefer-snapshot-hint.test.ts
src/rules/prefer-snapshot-hint.ts

fix(prefer-snapshot-hint): support passing hint to `toMatchSnapshot` as first argument

---

src/rules/__tests__/prefer-snapshot-hint.test.ts
src/rules/prefer-snapshot-hint.ts

fix(prefer-snapshot-hint): don't report multi snapshots in different tests within the same describe

---

docs/rules/valid-expect.md

- corrected pattern in `valid-expect` doc

docs(valid-expect): call `Promise.all` in example correctly

---

README.md

I realised we never actually did this even though we talked about it in #934

docs: add section about using overrides to apply rules to just test-related files

---

README.md
docs/rules/no-conditional-expect.md
docs/rules/no-deprecated-functions.md
docs/rules/no-identical-title.md
docs/rules/no-jasmine-globals.md
docs/rules/no-jest-import.md
docs/rules/no-large-snapshots.md
docs/rules/no-standalone-expect.md
docs/rules/prefer-comparison-matcher.md
docs/rules/prefer-equality-matcher.md
docs/rules/prefer-hooks-on-top.md
docs/rules/prefer-lowercase-title.md

Only contains spelling and grammar fixes, and not opinion-based conciseness or sentence structure changes.

docs: grammar and spelling fixes

---

src/rules/__tests__/prefer-expect-assertions.test.ts
src/rules/prefer-expect-assertions.ts

tbh this was pretty silly to have missed - a bit surprised it wasn't caught sooner 😅 
Fixes #1088

fix(prefer-expect-assertions): properly handle checking across multiple tests

---

src/rules/__tests__/no-focused-tests.test.ts
src/rules/__tests__/prefer-snapshot-hint.test.ts
src/rules/__tests__/valid-describe-callback.test.ts
src/rules/__tests__/valid-expect-in-promise.test.ts
src/rules/consistent-test-it.ts
src/rules/expect-expect.ts
src/rules/max-nested-describe.ts
src/rules/no-conditional-expect.ts
src/rules/no-conditional-in-test.ts
src/rules/no-done-callback.ts
src/rules/no-duplicate-hooks.ts
src/rules/no-export.ts
src/rules/no-focused-tests.ts
src/rules/no-hooks.ts
src/rules/no-identical-title.ts
src/rules/no-if.ts
src/rules/no-standalone-expect.ts
src/rules/no-test-prefixes.ts
src/rules/no-test-return-statement.ts
src/rules/prefer-expect-assertions.ts
src/rules/prefer-hooks-on-top.ts
src/rules/prefer-lowercase-title.ts
src/rules/prefer-snapshot-hint.ts
src/rules/prefer-todo.ts
src/rules/require-hook.ts
src/rules/require-top-level-describe.ts
src/rules/valid-describe-callback.ts
src/rules/valid-expect-in-promise.ts
src/rules/valid-title.ts

Per https://github.com/jest-community/eslint-plugin-jest/pull/1094#issuecomment-1126603712:
Turns out that `context.getScope` is stateful, being based on the same logic that the AST walker follows - effectively it should be through of as an argument like `node`, e.g. `CallExpression(node, scope)`.
I've chucked in some tests for a few rules, but I don't want to over saturate our tests with the same extensive subset of tests - I'll add a few more in once I've done #1106 because then the logic should be a bit easier to think about anyway (right now it's a little weird as it's still name-based).

fix: use correct scope for checking references

---

.github/workflows/smoke-test.yml

Currently smoke-test is failing because we're on jest v28 which isn't yet supported by `jest-runner-eslint` (it needs a new release) and npm v7+ enforces peer dependencies - I'd like to try and run the smoke test before I merge #1109 to see if there's any other cases, so this switches us to use `--legacy-peer-deps` which'll hopefully unblock the smoke test workflow

ci: use legacy peer dependencies for smoke test

---

src/rules/__tests__/utils.test.ts
src/rules/utils.ts

I've thought up a few more theoretical ways that you can have multiple definitions but so far none that are actually valid so vanilla ESLint errors on them and while TypeScript parses them they're not valid.
I have changed the code to grab the _last_ definition, because I think that is technically the more correct one (e.g. for function overloads the last definition has to be the implementation, even though there's no way that'll be something we care about here) & it's cheap.
Resolves #1108

fix: use the last reference definition when checking jest fn scope

---

src/rules/__tests__/no-deprecated-functions.test.ts
src/rules/__tests__/prefer-comparison-matcher.test.ts
yarn.lock

I [improved the logic in `eslint-plugin-eslint-plugin` for detecting uses of `RuleTester`](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/249), so now it checks in sub-blocks 🎉

chore: upgrade `eslint-plugin-eslint-plugin`

---

src/rules/__tests__/no-disabled-tests.test.ts
src/rules/no-disabled-tests.ts

To be merged after #1122 is landed
Resolves #1115

fix(no-disabled-tests): switch to using jest function call parser

---

src/rules/__tests__/no-disabled-tests.test.ts
src/rules/no-disabled-tests.ts

I somehow missed this when doing #1125

fix(no-disabled-tests): use jest function call parser for checking number of args

---

src/rules/utils/__tests__/parseJestFnCall.test.ts
src/rules/utils/parseJestFnCall.ts

I was trying to be a little clever, but there's a reason why `getNodeName` does this...
I've also included removing allowing `NewExpression` because that's also not correct.
Resolves #1128
Resolves #1130

fix: don't consider method calls on literals or `new` to be jest functions

---

src/rules/__tests__/no-alias-methods.test.ts
src/rules/__tests__/prefer-strict-equal.test.ts
src/rules/__tests__/prefer-to-be.test.ts
src/rules/__tests__/prefer-todo.test.ts
src/rules/no-alias-methods.ts
src/rules/prefer-strict-equal.ts
src/rules/prefer-to-be.ts
src/rules/prefer-todo.ts
src/rules/utils/misc.ts

Very minor (I really don't think anyone is accessing properties this way) but it's technically a bug - I realised afterwards that the alternative is to do:
```
fixer.replaceTextRange(
[matcher.node.object.range[1], matcher.node.range[1]],
`.${...}`,
),
```
which ensures the whole accessor is removed correctly making it safe to not use quotes - I'm not fussed which fix we actually do, but felt this helper was slightly better by way of being more readable 🤷 
We could be using it in `no-deprecated-functions` too except that technically isn't using a node of type `AccessorNode` so have left it as-is for now since it technically should be refactored anyway to use the new jest function parser.

fix: produce valid code when when fixing properties accessed with square brackets

---

src/rules/utils/__tests__/parseJestFnCall.test.ts
src/rules/utils/parseJestFnCall.ts

fix: don't consider template tags in the middle of a possible jest function chain to be valid

---

src/rules/__tests__/expect-expect.test.ts
src/rules/expect-expect.ts

fix(expect-expect): include numbers when matching assert function names with wildcards

---

src/rules/__tests__/no-disabled-tests.test.ts
src/rules/no-disabled-tests.ts

fix(no-disabled-tests): don't report on `it.todo` & `test.todo`

---

src/rules/__tests__/no-restricted-matchers.test.ts
src/rules/no-restricted-matchers.ts

I realised this while working on switching all the rules over to using `parseJestFnCall` for `expect` calls.

fix(no-restricted-matchers): allow restricting negated `resolves` and `rejects` modifiers

---

src/rules/__tests__/prefer-comparison-matcher.test.ts
src/rules/prefer-comparison-matcher.ts

`prefer-equality-matcher` suffers from the same bug, and should hopefully have roughly the same fix.

fix(prefer-comparison-matcher): handle `resolves` and `rejects` modifiers correctly

---

src/rules/__tests__/prefer-equality-matcher.test.ts
src/rules/prefer-equality-matcher.ts

Pretty much the same fix as #1145

fix(prefer-equality-matcher): handle `resolves` and `rejects` modifiers correctly

---

README.md
docs/rules/unbound-method.md
src/rules/unbound-method.ts
yarn.lock

They've removed an `s` which gave a diff in our generated docs

chore: update ts-eslint

---

docs/rules/prefer-hooks-in-order.md

It seems to specify a url that does not exist in the documentation for v27 and higher versions.
Perhaps it would be better to change the link to https://jestjs.io/docs/setup-teardown#order-of-execution.

docs(prefer-hooks-in-order): update the url of the reference link to match the latest version

---

README.md

The current logo path returns a 404, this PR updates to use the new ESLint logo location.
Current:
Updated:

docs: update ESLint logo

---

src/rules/__tests__/prefer-comparison-matcher.test.ts
src/rules/__tests__/prefer-equality-matcher.test.ts
src/rules/__tests__/prefer-to-contain.test.ts
src/rules/prefer-comparison-matcher.ts
src/rules/prefer-equality-matcher.ts
src/rules/prefer-to-contain.ts

This is the tiniest of "fixes" but it reduces the diff of #1173 a little - I don't think the matcher node is actually the best location to be reporting it, but it's still better than the modifier/negation node in all cases...

chore: change rules to always report on matcher even when modifier is present

---

src/rules/__tests__/prefer-called-with.test.ts
src/rules/prefer-called-with.ts

This reduces the diff in #1173 a little but it also technically an improvement on its own since it makes our message formatting consistent by adding spaces around the braces.

refactor(prefer-called-with): rename `name` data property to `matcherName`

---

README.md
docs/rules/prefer-mock-promise-shorthand.md
src/__tests__/__snapshots__/rules.test.ts.snap
src/__tests__/rules.test.ts
src/rules/__tests__/prefer-mock-promise-shorthand.test.ts
src/rules/prefer-mock-promise-shorthand.ts

I've decided not to do `jest.fn(...)` because it's sort of an odd duck where I could the case being made that people want to stick with using `mockImplementation` when they're using the other methods for consistency + that `jest.fn(() => Promise.resolve(...))` is not as much improved being written as `jest.fn().mockResolvedValue(...)` as what this rule currently covers.
Resolves #104

feat: create `prefer-mock-promise-shorthand` rule

---

.eslintrc.js
package.json
yarn.lock

Goodnight, sweet prince 😞 
One day I might be able to bring this plugin back if ESLint ever supports async rules (as they removed the sync version of the API that this plugin was using)

chore: remove `eslint-plugin-eslint-config` as it doesn't work with ESLint 8

---

src/rules/__tests__/no-standalone-expect.test.ts
src/rules/no-standalone-expect.ts

Resolves #1186
Resolves #1189
Resolves #1190

fix(no-standalone-expect): only report on `expect.hasAssertions` & `expect.assertions` member calls

---

src/rules/utils/parseJestFnCall.ts

This adds caching to _greatly_ reduce the cost of `parseJestFnCall` - currently most rules now sit around the 300-700ms mark, and this takes them down to about ~30ms (after the initial hit).
Running with `all` against the `jest` codebase:
```
TIMING=1 npx eslint --no-eslintrc --config my-eslint-config.cjs . --ext js,ts,tsx,jsx
```
before:
```
Rule                          | Time (ms) | Relative
:-----------------------------|----------:|--------:
jest/consistent-test-it       |   959.762 |     4.5%
jest/no-standalone-expect     |   866.172 |     4.0%
jest/prefer-expect-assertions |   854.663 |     4.0%
jest/no-conditional-expect    |   798.178 |     3.7%
jest/no-conditional-in-test   |   770.365 |     3.6%
jest/no-duplicate-hooks       |   767.634 |     3.6%
jest/no-identical-title …
```

perf: cache jest fn call parsing results

---

dangerfile.ts

I'm sure this should all work fine 😅 
@SimenB I'm going to merge this without waiting to see if it does actually work, but feel free to do a review post merge.

ci: update danger to do more stuff

---

src/rules/__tests__/prefer-mock-promise-shorthand.test.ts
src/rules/prefer-mock-promise-shorthand.ts

fix(prefer-mock-promise-shorthand): ignore `mockImplementation` functions that have parameters

---

dangerfile.ts

I'm pretty sure this is why labels are being created without the color - I've gone with `replace` because having the `#` means IDEs like IntelliJ/WebStorm will still show their colorpickers for the actual colors.

ci: remove `#` from label colors

---

src/rules/__tests__/prefer-expect-assertions.test.ts
src/rules/prefer-expect-assertions.ts

fix(prefer-expect-assertions): use scoped based jest fn call parser for `expect` checks

---

src/rules/__tests__/prefer-expect-assertions.test.ts
src/rules/prefer-expect-assertions.ts

fix(prefer-expect-assertions): report on concise arrow functions

---

.github/workflows/nodejs.yml
.github/workflows/prepare-cache.yml
.github/workflows/test.yml

@SimenB the OS is included in the cache key, so currently we're only generating a cache for `ubuntu` even though we're running on MacOS & Windows too.

ci: adjust caching to apply to all OSs

---

README.md
docs/rules/prefer-each.md
src/__tests__/__snapshots__/rules.test.ts.snap
src/__tests__/rules.test.ts
src/rules/__tests__/prefer-each.test.ts
src/rules/prefer-each.ts
src/rules/utils/parseJestFnCall.ts

Resolves #1048
There's a few improvements that could be made to this, like tracking if modifiers like `.skip` and `.only` are present, supporting `.forEach`, and even making suggestions, but for now I've kept it simple because those will be easy to add.

feat: create `prefer-each` rule

---

docs/rules/no-restricted-matchers.md
src/rules/__tests__/no-restricted-matchers.test.ts
src/rules/no-restricted-matchers.ts

BREAKING CHANGE
Resolves #1156
This messed my head up a little trying to come up with an intuitive interface that let you shortcut the config a bit i.e. by allowing `*` * `**`, but it always came out feeling brittle and hard to explain or dropping support for restricting modifiers; in the end I realised changing the check to just be `startsWith`  gets us what we want while being easy to understand.

feat(no-restricted-matchers): match based on start of chain, requiring each permutation to be set

---

src/rules/__tests__/unbound-method.test.ts
src/rules/unbound-method.ts

BREAKING CHANGE
Resolves #1172

fix(unbound-method): don't suppress errors from base rule

---

README.md
docs/rules/no-alias-methods.md
src/__tests__/__snapshots__/rules.test.ts.snap
src/rules/no-alias-methods.ts

BREAKING CHANGE: `no-alias-methods` is now recommended as the methods themselves will be removed in
the next major version of Jest
Per https://github.com/facebook/jest/issues/13164
I'm the fence about if we fold this into `no-deprecated-methods` as it would be mostly a copy & paste, but on the other hand I don't like the fact that this uses "methods" when really its "matchers" - still, I've stuck with the current rule for now because its the smaller change. (tbh it wouldn't be wrong to have both rules checking this for a while either 🤷 )

feat: make `no-alias-methods` recommended

---

src/rules/no-done-callback.ts
src/rules/no-focused-tests.ts
src/rules/prefer-equality-matcher.ts
src/rules/prefer-expect-assertions.ts
src/rules/prefer-strict-equal.ts

`meta.docs.suggestion` was replaced by `meta.hasSuggestions` as of ESLint v8: https://github.com/eslint/eslint/pull/14573
The old property was never used for anything, while the presence of the new property is [enforced](https://eslint.org/docs/latest/user-guide/migrating-to-8.0.0#suggestions) by ESLint when a rule provides suggestions.
It's confusing to leave the old, redundant property in place, so I have removed it here.

chore: remove obsolete `meta.docs.suggestion` property

---

src/rules/__tests__/prefer-expect-assertions.test.ts
src/rules/prefer-expect-assertions.ts

fix(prefer-expect-assertions): report on concise arrow functions with `expect` call

---

docs/rules/no-deprecated-functions.md

Some removal details could be update in `no-deprecated-functions` rule details.
Methods which were scheduled to be removed in Jest 27 are already gone. See #9853
And `jest.genMockFromModule` is now scheduled to be removed in Jest 30: https://github.com/facebook/jest/blob/0cfc2ad2991373324306c8daf962c41d0f37793c/packages/jest-environment/src/index.ts#L132-L142

docs: update removal details in `no-deprecated-functions`

---

src/rules/__tests__/no-restricted-matchers.test.ts
src/rules/no-restricted-matchers.ts

fix(no-restricted-matchers): improve check to not be solely based on the start of the matcher chain

---

README.md

The file was moved in [#4124](https://github.com/typescript-eslint/typescript-eslint/pull/4124/files#diff-8944263dcd09a73a257ea659489d62a3d2093d100c89dafcd8c3ba371855f2e6).

docs: fix link to typed linting in README

---

eslint-remote-tester.config.ts

ci: disable `jest/unbound-method` in smoke test

---

src/__tests__/__snapshots__/rules.test.ts.snap
src/index.ts

This lets us avoid having to do ugly things in #1226 when accessing `configs[config].rules[rule]` (which currently we're `@ts-ignore`-ing) because it makes all configs of the same type.
I've labeled this as a fix because I think that is technically true given we're being inconsistent vs the other configs; this also could arguably be a breaking change and we have also spoken about removing the globals at some point once we had proper scope resolving.
@SimenB will wait for you to weight in on if you're happy to land this or if you think it should be in a major version (in which case I'll do something different)

fix: ensure jest globals are enabled in `styles` config

---

package.json
src/index.ts
src/rules/no-commented-out-tests.ts
src/rules/no-conditional-in-test.ts
src/rules/no-mocks-import.ts
src/rules/prefer-each.ts
src/rules/prefer-lowercase-title.ts
src/rules/require-top-level-describe.ts
src/rules/utils/__tests__/detectJestVersion.test.ts
src/rules/utils/__tests__/parseJestFnCall.test.ts
src/rules/utils/detectJestVersion.ts
tools/regenerate-docs.ts
tsconfig.json
yarn.lock

#1226 fails CI due to "missing" `flatMap` - instead of manually defining `lib` etc., extending `@tsconfig/node14` seems cleaner

chore: use `@tsconfig/node14` and stricter TS config

---

docs/rules/prefer-expect-resolves.md
src/rules/__tests__/prefer-expect-resolves.test.ts

Credit goes to @fauxbytes for noticing this 😅

docs(prefer-expect-resolves): adjust incorrect example snippet

---

README.md
docs/rules/no-restricted-jest-methods.md
src/__tests__/__snapshots__/rules.test.ts.snap
src/__tests__/rules.test.ts
src/rules/__tests__/no-restricted-jest-methods.test.ts
src/rules/no-restricted-jest-methods.ts

feat: create `no-restricted-jest-methods` rule

---

docs/rules/no-restricted-jest-methods.md

There was a minor typo in the description
`curtain` vs. `certain` 😉 
see https://github.com/jest-community/eslint-plugin-jest/pull/1257#pullrequestreview-1129892834

docs: correct typo in description

---

src/rules/__tests__/prefer-to-be.test.ts
src/rules/prefer-to-be.ts

Hello,
I felt like `prefer-to-be` rule should support also negative numbers so I **tried** to implement it. I will be glad for feedback and improvement suggestions. I'm also not sure if it's feature or bug.

fix(prefer-to-be): support negative numbers

---

src/rules/valid-expect-in-promise.ts

Fix a typo in `valid-expect-in-promise` that uses [`it's` as a possessive instead of the correct `its`](https://www.merriam-webster.com/words-at-play/when-to-use-its-vs-its):
```
17:5  error  This promise should either be returned or awaited to ensure the expects in it's chain are called  jest/valid-expect-in-promise
```

Fix typo: possessive it's should be its

---

CHANGELOG.md

I can't fix it in the actual commit, but at least it'll be resolved here 🤷

docs: use correct spelling of "grammar"

---

src/rules/__tests__/no-restricted-jest-methods.test.ts
src/rules/no-restricted-jest-methods.ts

fix(no-restricted-jest-methods): don't crash on `jest()`

---

src/rules/utils/parseJestFnCall.ts

Huge thanks to @SLKnutson for pointing this out - this is mainly a win for larger codebases, since we still have to loop until we find the information we need (or don't), but it is definitely faster
Before, completed in ~30 seconds:
```
Rule                            | Time (ms) | Relative
:-------------------------------|----------:|--------:
jest/consistent-test-it         |   919.565 |     5.3%
jest/prefer-expect-assertions   |   714.352 |     4.1%
jest/no-conditional-expect      |   626.779 |     3.6%
jest/no-standalone-expect       |   612.223 |     3.5%
jest/prefer-lowercase-title     |   608.857 |     3.5%
jest/no-identical-title         |   599.639 |     3.4%
jest/no-disabled-tests          |   587.099 |     3.4%
jest/prefer-each                |   586.834 |     3.4% …
```

perf: don't collect more info than needed when resolving jest functions

---

.github/workflows/lint.yml
.github/workflows/nodejs.yml

The hardening done in #1249 was incomplete - this should resolve that.

ci: adjust permissions so that comments can be put on prs and issues

---

src/rules/utils/parseJestFnCall.ts

Follow on to #1274 & #1275 - in theory this is faster but it has no noticeable impact on performance so I'm marking this as a refactor rather than `perf`.
The actual reason I'm doing it in the first place is because it makes the codebase a little smaller and we don't really need the two functions anymore.

refactor: inline `collectReferences` utility into `scopeHasLocalReference`

---

src/rules/valid-title.ts

`substr` is actually non-spec - its very unlikely to ever go away, but we're using `substring` everywhere else and IDEs flag it as deprecated so might as well change our sole usage of it

refactor(valid-title): use `substring` instead of `substr`

---

.husky/commit-msg
.husky/pre-commit

v8.0.0 of Husky fixed shell path and args for newly created git hooks, but doesn't update existing ones, so have done that here.
See https://github.com/typicode/husky/pull/1051 and https://github.com/typicode/husky/pull/1132

chore(.husky): shell path and arg updates

---

.github/workflows/lint.yml
.github/workflows/markdown-link-check.yml
.github/workflows/nodejs.yml
.github/workflows/prepare-cache.yml
.github/workflows/smoke-test.yml
.github/workflows/test.yml

This PR removes Git credentials/SSH keys after checkout as a security precaution by setting `persist-credentials` to false, they are not used after the initial checkout.
Due to git being used in the `docs` job in the nodejs workflow, it has not been removed there:
https://github.com/jest-community/eslint-plugin-jest/blob/ad04fcc97b5dcc676c5bd2152f84608c08e0c50a/.github/workflows/nodejs.yml#L125-L128

ci: remove git credentials after checkout

---

src/rules/__tests__/no-done-callback.test.ts
src/rules/__tests__/prefer-comparison-matcher.test.ts
src/rules/__tests__/prefer-equality-matcher.test.ts
src/rules/__tests__/prefer-expect-assertions.test.ts
src/rules/__tests__/prefer-expect-resolves.test.ts
src/rules/__tests__/prefer-mock-promise-shorthand.test.ts
src/rules/__tests__/prefer-spy-on.test.ts
src/rules/__tests__/prefer-strict-equal.test.ts
src/rules/__tests__/prefer-to-be.test.ts
src/rules/__tests__/prefer-to-contain.test.ts
src/rules/__tests__/prefer-to-have-length.test.ts
src/rules/__tests__/prefer-todo.test.ts
src/rules/no-done-callback.ts
src/rules/prefer-expect-assertions.ts
src/rules/prefer-to-be.ts
src/rules/utils/misc.ts

The fix that no one asked for 😄 props to @berkinanik for bring this to my attention over in `eslint-plugin-jest-dom`.
Weirdly ESLint doesn't seem to think some of the result syntax before this is invalid (namely in `no-done-callback` which'd give `((), ) => {}`), but didn't feel like digging into that further right now.

fix: ensure rule fixes produce valid code when function params and args have trailing commas

---

.eslint-doc-generatorrc.js
package.json

I've created https://github.com/bmish/eslint-doc-generator/issues/260 about supporting TypeScript for config, but for now JS will do.
Currently we don't actually check JS files with TS, but will do that in another PR since it affects a few other files.

chore: switch to using config file to configure `eslint-doc-generator`

---

README.md
docs/rules/no-untyped-mock-factory.md
src/__tests__/__snapshots__/rules.test.ts.snap
src/__tests__/rules.test.ts
src/rules/__tests__/no-untyped-mock-factory.test.ts
src/rules/no-untyped-mock-factory.ts

Closes #1313
While the rule itself doesn't need type-checking, the auto-fix does. It it possible to disable the auto-fix based on the parser & source file? If not, the rule could be switched to use editor suggestions.

feat(require-typed-module-mocks): add rule to use strict module mock factory types

---

CHANGELOG.md

I forgot to update the title of #1314 before merging, so it had the old rule name

docs: update rule name in changelog

---

src/index.ts

This is a tiny change to use [`Object.fromEntries`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries) (supported in Node 12+) instead of a `.reduce` loop. 
This improves performance a little by making it a O(n) instead of O(n^2) operation, since spreading the accumulator means creating a new object each iteration of the loop.

refactor: use `Object.fromEntries` to build rule config maps

---

docs/rules/no-if.md
yarn.lock

docs: update `eslint-doc-generator`

---

src/rules/__tests__/valid-expect-in-promise.test.ts
src/rules/prefer-spy-on.ts
src/rules/valid-expect-in-promise.ts
yarn.lock

Found via https://github.com/typescript-eslint/typescript-eslint/pull/6257 - also unblocks #1318

fix(valid-expect-in-promise): handle sparse arrays

---

docs/rules/require-hook.md

The intro to [require-hook.md](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/require-hook.md) has repeated information, this PR removes the extra copy.

docs(require-hook): remove redundant section

---

docs/rules/no-large-snapshots.md

docs(no-large-snapshots): mention `--ext snap`

---

package.json
yarn.lock

It's already declared as optional.
We load it here: https://github.com/jest-community/eslint-plugin-jest/blob/197e986e2290530fd8a807d3de2f9298de74e8e5/src/rules/utils/detectJestVersion.ts#L30

fix: add missing (optional) peer dependency on Jest

---

package.json
yarn.lock

We're no longer actually using `prettier` programmatically so don't need the types for it.

chore: remove unneeded types for prettier

---

.github/workflows/nodejs.yml

ci: test against v5 and v6 of `@typescript-eslint/eslint-plugin`

---

docs/rules/valid-title.md
src/rules/__tests__/valid-title.test.ts
src/rules/valid-title.ts

We use BDD style test names and want some trailing space for formatting
```js
describe('Feature: ...', () => {
it(`GIVEN ...
WHEN ...
THEN ...
`, () => {
// test body
});
});
```

feat(valid-title): support ignoring leading and trailing whitespace

---

src/rules/__tests__/no-focused-tests.test.ts
src/rules/no-focused-tests.ts

Currently for `.only` we report on that identifier itself, whereas for `fit` and `fdescribe` we report on the whole call expression - while arguably reporting on the call expression is more accurate since we're about about the test as a whole being skipped, some editors handle reporting on call expressions poorly.

fix(no-focused-tests): make reporting location consistent

---

src/rules/max-expects.ts
src/rules/max-nested-describe.ts
src/rules/no-export.ts
src/rules/no-focused-tests.ts
src/rules/no-identical-title.ts
src/rules/no-if.ts
src/rules/no-mocks-import.ts
src/rules/no-standalone-expect.ts
src/rules/no-test-return-statement.ts
src/rules/prefer-expect-resolves.ts
src/rules/prefer-spy-on.ts
src/rules/valid-expect.ts
src/rules/valid-title.ts

As far as I know ESLint does not have an official stance on the punctuation of rule messages, but in my experience it makes more sense to not end with a full stop because tools either display the rule at the end of their message (e.g. "<message> (<rule>)") or have nothing (such as in GitHub Actions annotations, iirc) - either way this at least makes us consistent, and we can invert it later if I turn out to be wrong 🤷

fix: make rule message punctuation consistent

---

package.json
src/rules/utils/__tests__/detectJestVersion.test.ts
yarn.lock

For some reason when running these tests on Jest v29.2.1 and Node v20.6.0 they fail because of coloring - this doesn't cause problems in CI as color output is disabled nor does it happen if we use `toStrictEqual` but that felt wrong since we have a rule called `prefer-to-be`...

test(detectJestVersion): strip ansi before comparing

---

src/rules/__tests__/expect-expect.test.ts
src/rules/expect-expect.ts

Resolves #654
Resolves #641
Resolves #539

fix(expect-expert): report on test function identifier rather than body

---

docs/rules/valid-title.md
src/rules/__tests__/valid-title.test.ts
src/rules/valid-title.ts

feat(valid-title): allow disabling titleMustBeString on test titles

---

tsconfig.json

I'm honestly still trying to wrap my head around these new settings, but this is required for `@typescript-eslint/utils` v6 and doesn't seem to result in any different output (which makes sense since we're compiling with Babel) so I think this is safe to land.

chore: update `moduleResolution` and `module` to `node16`

---

src/index.ts

Relates to #1408
See https://eslint.org/docs/latest/extend/plugin-migration-flat-config#adding-plugin-meta-information
It seems like this is backwards compatible - I've at least done a quick test with an older version of ESLint and it didn't care 🤷

feat: include plugin `meta` information for ESLint v9

---

package.json
yarn.lock

Another one to unblock #1467 - it seems TS 5.3 is broken via `ts-node` somehow. Probably what made #1471 happen as well.
EDIT: yeah: https://github.com/TypeStrong/ts-node/pull/2091

chore: avoid TypeScript 5.3

---

src/processors/snapshot-processor.ts

Related to #1454
While not stated in eslint's (incomplete) migration guide, the meta object is explicitly required by the [flat config source](https://github.com/eslint/eslint/blob/2a8eea8e5847f4103d90d667a2b08edf9795545f/lib/config/flat-config-array.js#L223).

fix: include plugin `meta` information with snapshot processor for ESLint v9

---

src/index.ts
src/rules/expect-expect.ts
src/rules/no-commented-out-tests.ts
src/rules/no-conditional-expect.ts
src/rules/no-confusing-set-timeout.ts
src/rules/no-disabled-tests.ts
src/rules/no-done-callback.ts
src/rules/no-if.ts
src/rules/no-jasmine-globals.ts
src/rules/no-large-snapshots.ts
src/rules/no-test-return-statement.ts
src/rules/prefer-comparison-matcher.ts
src/rules/prefer-equality-matcher.ts
src/rules/prefer-mock-promise-shorthand.ts
src/rules/prefer-spy-on.ts
src/rules/prefer-to-contain.ts
src/rules/utils/misc.ts
src/rules/utils/parseJestFnCall.ts

Per https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/
Marking as a draft for now since there isn't an immediate need to land this and I want to dig a bit deeper into ESLint v9 etc in case there are other deprecations that might be upcoming.

fix: replace use of deprecated methods

---

tsconfig.json

This was because of a change in `prettier` that has then been reverted

chore: format `tsconfig.json`

---

.github/workflows/nodejs.yml
package.json
yarn.lock

feat: allow `@typescript-eslint` v7

---

.github/workflows/nodejs.yml

While the tests are passing, it's not officially supported for v7 and excluding it saves us a few CI jobs in the matrix.

ci: don't test `@typescript-eslint` v7 against Node v19

---

src/processors/__tests__/snapshot-processor.test.ts
src/processors/snapshot-processor.ts

Mostly useful because it means we're more compatible with the `Plugin` type which I'm using in another branch

refactor: use types from `@typescript-eslint/utils` for snapshot processor

---

.yarn/patches/@typescript-eslint-typescript-estree-npm-5.62.0-5d1ea132a9.patch
package.json
yarn.lock

Using 5.3 or 5.4 breaks due to https://github.com/typescript-eslint/typescript-eslint/issues/8047
We need to upgrade to v6 (or v7) in order to get the fix.
For now I've just patched the library

chore: upgrade to TS 5.4

---

src/index.ts

Rule metadata is really typed for how `@typescript-eslint` use it and their recent majors have changed exports so we can't actually argument their interfaces anymore so this switches us to just using a static object.
I've _not_ done anything fancy like having dedicated files in `configs/` because I don't think there's a big advantage at this point and frankly I just want to push through to the ESLint v9 / `@typescript-eslint` v<whatever> (I think 7..?) so will revisit restructuring later once the dust has settled.
I've also not removed the actual properties from the rules as I think that technically could be a breaking change? but I have at least tested without them locally to ensure all the scripts and workflow still work.

refactor: make config rules static rather than based off rule metadata

---

src/rules/__tests__/no-done-callback.test.ts

ESLint v9 cares about these, and it's not wrong - relates to #1534

test(no-done-callback): add missing `suggestions` to `each` cases

---

src/rules/no-done-callback.ts
src/rules/no-large-snapshots.ts

refactor: address missed usage of deprecated `context.getFilename` in rules

---

src/rules/__tests__/prefer-expect-assertions.test.ts

ESLint v9 cares about these, and it's not wrong - relates to #1534

test(prefer-expect-assertions): add missing `suggestions` to `each` cases

---

src/rules/__tests__/prefer-expect-assertions.test.ts

ESLint v9 cares about these, and it's not wrong - relates to #1534

test(prefer-expect-assertions): add missing suggestions

---

src/rules/__tests__/prefer-comparison-matcher.test.ts

ESLint v9 cares about these, and it's not wrong - relates to #1534

test(prefer-comparison-matcher): update names and remove duplicates

---

src/__tests__/rules.test.ts
src/rules/__tests__/no-deprecated-functions.test.ts
src/rules/__tests__/prefer-comparison-matcher.test.ts
src/rules/utils/misc.ts

I realised this while doing #1540 - shaves off a few lines which is nice

refactor: use `flatMap` instead of `reduce`

---

src/rules/no-large-snapshots.ts

Cherry picked from https://github.com/jest-community/eslint-plugin-jest/pull/1534 - it seems that globals are different in ESLint v9 resulting in the same issue with `instanceof` that Jest has (https://github.com/jestjs/jest/issues/2549); it should be fine to switch the check to checking for a string (in fact it's arguably better as it means people could provide their own custom object with a `test` function 🤷)

fix(no-large-snapshots): avoid `instanceof RegExp` check for ESLint v9 compatibility

---

.github/workflows/nodejs.yml
package.json

BREAKING CHANGE: Node v19 is no longer supported

fix: drop support for Node 19

---

src/rules/__tests__/max-expects.test.ts
src/rules/max-expects.ts

fix(max-expects): properly reset counter when exiting a test case

---

README.md
src/rules/utils/__tests__/parseJestFnCall.test.ts
src/rules/utils/parseJestFnCall.ts

Resolves #1431
I'm purposely not adding support to `prefer-importing-jest-globals` in this PR because it's a little weird, but I've got that locally and might just do a PR straight afterwards.

feat: support providing aliases for `@jest/globals` package

---

dangerfile.ts

I think this will be better for most pull requests since conventional commits tends to mean either applying at the pull request level or only ever doing one commit; in practical terms, this means we can use cc in the context of a pull requests commits without getting both the "enhancement" and "bug" label.
Really it probably makes sense to skip checking commits in most cases or even throw/post an error, but for now I've not done that because I expect the fallback to be triggered by external contributors and this workflow currently will only run when a new change it pushed; we could change that but given how stable we are these days I'm not going to do that for now.

ci: prioritize labelling pull requests based on their title rather than their commits

---

package.json
yarn.lock

Per https://github.com/jest-community/eslint-plugin-jest/pull/1547#discussion_r1554656720
We still support v9 but this means local linting will still work

chore: remove `eslint` v9 as a dev dependency for now

---

src/rules/expect-expect.ts

This doesn't need to be an array since we only allow one type of item.

refactor(expect-expect): remove unneeded array

---

docs/rules/prefer-importing-jest-globals.md
src/rules/__tests__/prefer-importing-jest-globals.test.ts
src/rules/prefer-importing-jest-globals.ts

Accessing the `jest` global in ESM must be done either through `import.meta.jest` or by importing it from `@jest/globals`. The latter is useful while migrating to ESM because the former is not accessible in non-ESM.
This adds an option to specify the types of globals for which we want to enforce the import.

feat: prefer importing jest globals for specific types

---

src/rules/prefer-importing-jest-globals.ts

I missed this during review/refactoring 😅

refactor(prefer-importing-jest-globals): use `AST_NODE_TYPES` constant instead of string literal

---

src/rules/prefer-lowercase-title.ts
src/rules/utils/__tests__/detectJestVersion.test.ts
src/rules/utils/__tests__/parseJestFnCall.test.ts
src/rules/valid-title.ts

As per the comment in https://github.com/jest-community/eslint-plugin-jest/pull/1573, I have removed the unnecessary `as const`.

refactor: remove unnecessary 'as const'

---

README.md
docs/rules/valid-expect.md
src/rules/__tests__/valid-expect.test.ts
src/rules/valid-expect.ts

When `await` is missing ,  it's adding `await`.
Relates to https://github.com/jest-community/eslint-plugin-jest/issues/1140

feat(valid-expect): supporting automatically fixing missing `await` in some cases

---

package.json

`main` is finally supported out of the box: https://github.com/semantic-release/semantic-release/pull/1737#issuecomment-2105027110

chore: remove `semantic-release` branch config

---

yarn.lock

A bit too quick in #1585 - I just assumed we were using `npx semantic-release` 😅

chore: update semantic release

---

jest.config.ts

I've not dug into the actual code yet, but I'm pretty sure this is why #1590 is failing CI - more specifically, the latest version of `eslint-plugin-n` (which does not support ESLint v7) is now doing something v7 doesn't support

test: only run linting when using ESLint v8

---

README.md

Renovate keeps merging PRs with failing CI 🙁 
I've added some required CI checks to the repo's config now (LTS on all 3 OSes, typescript and prettier), so hopefully that won't happen again
https://github.com/jest-community/eslint-plugin-jest/pull/1603

chore: run prettier

---

README.md
src/rules/__tests__/valid-expect.test.ts
src/rules/valid-expect.ts

feat(valid-expect): supporting automatically fixing adding async in some cases

---

.github/workflows/nodejs.yml

I'm guessing this job was made required as part of trying to get Renovate to stop merging PRs that are failing CI

ci: run `docs` job on `push`

---

src/rules/prefer-jest-mocked.ts

refactor: use shorthanded object property

---

src/rules/__tests__/test-utils.ts

`@typescript-eslint/array-type` has gotten smarter in the latest version of v7, so this makes it happy

refactor: use simple array syntax

---

tsconfig.json

Currently our typechecking is failing due to a conflict between the latest TypeScript and `@typescript-eslint/typescript-estree` v6 - this unblocks us without needing to immediately drop support for that version

chore: skip lib checks for now

---

.eslintrc.js
.github/workflows/nodejs.yml
jest.config.ts
package.json
yarn.lock

Unsurprisingly we don't have to actually do anything for this support - I'm not worried about the `unbound-method` tests as [this weirdness happened before](https://github.com/jest-community/eslint-plugin-jest/pull/1534#issuecomment-2027752670) and I plan to do a new major soon which'll get all this cleaned up; everything is working fine locally
Resolves #1633
Resolves #1623

feat: allow `@typescript-eslint` v8

---

src/rules/prefer-importing-jest-globals.ts

This pr is to remove unused `ImportDeclaration` check.

perf(prefer-importing-jest-globals): stop collecting import specifiers for no reason

---

src/rules/__tests__/prefer-importing-jest-globals.test.ts
src/rules/prefer-importing-jest-globals.ts

The current fixer implementation for prefer-importing-jest-globals inserts the `import` directly before the reporting node. This works fine when the reporting node is a function call.
```
describe(...)
```
results in
```
import { describe } from 'jest/globals';
describe(...)
```
But it breaks when the reporting node is part of a variable declaration
```
const onClick = jest.fn();
```
results in 
```
const onClick = import { jest } from '@jest/globals';
jest.fn();
```
This change updates the fixer so new imports are inserted at the top of the file.
```
console.log('foo');
const onClick = jest.fn();
```
results in 
```
import { jest } from '@jest/globals';
console.log('foo')
const onClick = jest.fn();
```
Existing imports are unchanged
```
console.log('foo');
import { describe } from …
```

fix(prefer-importing-jest-globals): don't add imports in the middle of statements

---

yarn.lock

It seems Renovate does not actually run `yarn install` when it upgrades Yarn? This came in from #1643

build: update hash for `typescript` after yarn upgrade

---

README.md

docs: include both flat and legacy config examples in usage section

---

package.json
yarn.lock

While reviewing #1665 I realised that we should actually be using v16 😅

chore: switch to v16 of `@types/node`

---

.eslintrc.js
index.d.ts
package.json

Fixes https://github.com/jest-community/eslint-plugin-jest/issues/1469
I opted to generate the types manually with a hard coded `index.d.ts` file given that the types are very straightforward and the result works much better with typescript-eslint in my experience vs simply relying on `tsc` generated types.

feat: add types to package

---

package.json

Re-PR of https://github.com/jest-community/eslint-plugin-jest/pull/1673, with `npx sort-package-json` ran.
> The repository URL was fixed by simply running `npm pkg fix`, which is [what `npm publish` does prior to publishing](https://docs.npmjs.com/cli/v10/commands/npm-pkg#description).
> 
> The addition of the [`homepage`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json?v=true#homepage) property allows for the URL to the repo to be correctly displayed when hovered over in VS Code when using a proxy registry like in Azure DevOps:
> 
> ![image](https://private-user-images.githubusercontent.com/43814140/387210314-6ab18758-5335-46ed-843b-c8ac3e40c1c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTU …

chore: update package urls for homepage, repository, and bugs

---

.github/workflows/markdown-link-check.yml
package.json
yarn.lock

[It seems that something is broken with the latest version(s)](https://github.com/tcort/markdown-link-check/issues/369) when using a config file; in the long-run it might be best to migrate to another tool but for now this should get our CI passing.
I've also removed the `-q(uiet)` flag in CI since logs are free and that could make it easier to debug in future
Resolves #1696

chore: downgrade `markdown-link-check` to known working version and make it louder

---

README.md
docs/rules/padding-around-test-blocks.md
src/rules/padding-around-test-blocks.ts

I have fixed the `padding-around-test-blocks` rule documentation.

fix(padding-around-test-blocks): update description

---

docs/rules/prefer-equality-matcher.md

There is a minor mistake in the docs which claims the following to be equivalent,
```js
expect(myObj !== thatObj).toStrictEqual(true);
```
```js
expect(myObj).toStrictEqual(thatObj);
```
where it should be
```js
expect(myObj).not.toStrictEqual(thatObj);
```

docs(prefer-equality-matcher): fix !== example

---

package.json
yarn.lock

Apparently we were depending on this implicitly (which surprises me), and #1708 updated `conventional-changelog-writer` to a version that no longer has this as a dependency, causing CI to fail in some cases because only some versions of `@typescript-eslint` depend on them.

chore: ensure types are available for `semver`

---

.eslint-doc-generatorrc.js

Added a missing `'use strict'` directive to the only CJS file in this repo without one.
Test failures unrelated, occurring on the main branch.

chore: add missing `'use strict'` directive

---

.eslintrc.js

ESLint pre-v9 ignores "hidden" files - that is, files prefixed with a dot (.) - meaning our rules were not being enforced; I believe this is not needed in ESLint v9, but while we're on v8 we can explicitly negate ignoring these files to have them linted

chore: lint "hidden" js files

---

.prettierignore

Sometimes I run `prettier` by itself manually, which currently tries to format `.yarn` 😅

chore: ignore `.yarn` directory when running `prettier`

---

src/rules/no-large-snapshots.ts

The incorrect message was introduced by #278

fix(no-large-snapshots): use a far better message for when an unexpected snapshot is found

---

src/rules/no-commented-out-tests.ts

The current message seems like a general observation rather than an indicator of an issue

fix(no-commented-out-tests): make message less ambiguous

---

src/rules/__tests__/prefer-ending-with-an-expect.test.ts
src/rules/prefer-ending-with-an-expect.ts

fix(prefer-ending-with-an-expect): don't report on `await expect`

---

src/rules/__tests__/prefer-importing-jest-globals.test.ts
src/rules/prefer-importing-jest-globals.ts

fix(prefer-importing-jest-globals): preserve `require` property renames

---

src/rules/__tests__/test-utils.ts
src/rules/utils/__tests__/parseJestFnCall.test.ts

How we're doing it currently isn't super bad or anything, but in other places we're just importing the `package.json` which is a lot smaller, and moving this into test utils makes it a lot easier to use in other tests (which I'll be doing shortly, though ironically this'll then go away very quickly after as we're dropping support for ESLint v7 which is what we need this for)

test: simplify detection of ESLint major version

---

src/rules/__tests__/test-utils.ts
src/rules/utils/__tests__/parseJestFnCall.test.ts

While arguably this is using our custom tester for more than it was intended, since we only have one condition when we skip tests which'll be going away soon but that I want to use in a few other places first, this will mean less work elsewhere

test: automatically skip ecma 2022 tests when using ESLint v7

---

src/rules/utils/detectJestVersion.ts

I don't think this needs a dedicated release since the specific value is mainly a vanity thing 😄

chore: add `30` to `JestVersion` type

---

src/rules/__tests__/prefer-importing-jest-globals.test.ts
src/rules/prefer-importing-jest-globals.ts

While there's no reason to actually do this for our identifiers, official support for this was added in `@typescript-eslint/parser` v8 meaning we need to handle this somehow, so this just preserves it 🤷

fix(prefer-importing-jest-globals): handle string-based import names

---

src/rules/utils/parseJestFnCall.ts

We should be able to do this now that we're using `@typescript-eslint` v8 in development and when typechecking

refactor: use declaration merging instead of casting for accessing plugin settings

---

tsconfig.json

We should be able to do this now that we're using `@typescript-eslint` v8 in development and when typechecking

chore: don't skip lib checks

---

docs/rules/no-alias-methods.md
docs/rules/no-deprecated-functions.md

"the next major version of Jest" is now out and its v30

docs: update references to Jest v30

---

package.json
src/rules/utils/__tests__/detectJestVersion.test.ts
yarn.lock

Initially I planned to replace this with `util.stripVTControlCharacters` but then I realized we can modify how our test works slightly to not need the processing at all

test: remove use of `strip-ansi`

---

package.json

This reverts #1585 which'll hopefully mean next time `semantic-release` will prefix the version with `-next` - I'm landing it as a `fix` so that it'll end up marking a v29.x.x version as the latest on `npm`

fix: update semantic-release config so new v29 major is marked as latest on `npm`

---

CHANGELOG.md

docs: remove duplicate changelog entry

---

src/rules/utils/__tests__/detectJestVersion.test.ts

Apparently #1770 only works in CI because that implies no color - I swear this worked locally too without these, but oh well

test: ensure that Node process does not output color

---

.eslintrc.js
eslint-remote-tester.config.ts

Since its a module we don't need `use strict`

chore: mark remote tester config as a module

---

jest.config.ts
src/rules/__tests__/unbound-method.test.ts

Now that we're just using `@typescript-eslint` v8 we need to have these tests running - I've resorted to disabling the 5 tests that fail when `CI=true`, as I've still not been able to figure out why that is, and they are passing when `CI=false` so I know it's a bug in the test side rather than our actual runtime code

test(unbound-method): run specs

---

.github/workflows/smoke-test.yml
eslint-remote-tester.config.ts
package.json
yarn.lock

Currently `npm` errors as we've technically got peer dependency violations due to [`jest-runner-eslint` not officially supporting Jest v30](https://github.com/jest-community/jest-runner-eslint/pull/291) (or ESLint v9 for that matter), so I've finally switched us to using Yarn to setup this job.
This has also revealed that we might not yet be able to use v2 of the repositories package so I've downgraded that for now but will revisit once the job is working again

ci: get smoketest workflow passing again

---

eslint.config.js
package.json
types.d.ts
yarn.lock

New rules disabled for now. Can follow-up individually to enable those.
- https://github.com/eslint-community/eslint-plugin-eslint-plugin/releases/tag/v7.0.0
The plugin now has TypeScript types included.

chore(deps): update to eslint-plugin-eslint-plugin v7

---

.github/workflows/lint.yml
.github/workflows/markdown-link-check.yml
.github/workflows/nodejs.yml
.github/workflows/prepare-cache.yml
.github/workflows/smoke-test.yml
.github/workflows/test.yml

We might as well do this since we're using Renovate so its easy to keep them up to date

ci: pin actions to shas

---

.github/renovate.json

This should be nicer than having a dedicated PR-per-workflow

ci: have renovate group GHA workflow updates into a single PR
